const API = '/api/ai-hot';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = id => `<svg aria-hidden="true"><use href="#${id}"/></svg>`;
const safe = v => {try {const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'#'}catch{return '#'}};
const preview = new URLSearchParams(location.search).get('preview') === '1';
const categories = [{key:'all',label:'全部'},{key:'ai-models',label:'模型'},{key:'ai-products',label:'产品'},{key:'industry',label:'行业'},{key:'paper',label:'论文'},{key:'tip',label:'教程'},{key:'opinion',label:'观点'}];
const views = {selected:['HANDPICKED FOR YOU','值得读的几条'],hot:['WHAT\'S HAPPENING','此刻的 AI 热点'],all:['EVERYTHING IN ONE PLACE','探索全部动态'],daily:['YOUR DAILY BRIEF','每日 AI 早报'],starred:['SAVED FOR LATER','留给下次的发现'],sources:['FOLLOW THE SOURCES','从源头，了解 AI']};
let view = new URLSearchParams(location.search).get('view') || 'selected';
if (!views[view]) view='selected';
let category='all', query='', offset=0, current=[], requestId=0;
let stars={};try{const saved=JSON.parse(localStorage.getItem('softcloud-ai-hot-stars'));if(saved&&typeof saved==='object'&&!Array.isArray(saved))stars=saved}catch{}
let reportArchive=[];
const mock = [
  {id:'example-1',title_zh:'示例：一个开源模型发布了新的能力与使用入口',summary_zh:'这里会用一段中文概括原文的核心事实，保留必要的版本、数字和开放方式。此处为虚构示例，仅用于展示阅读界面。',source_name:'示例官方信源',source_id:'example-source-a',published:Date.now()-3600000,category:'ai-models',score1:85,score2:83,selected:1,reason:'推荐理由会说明这条资料具体能帮助读者了解什么，并与摘要区分。',tags:'["模型发布","开源生态"]',url:'https://github.com/KKKKhazix/AIHOT'},
  {id:'example-2',title_zh:'示例：把新工具的工作流程，讲给普通用户听',summary_zh:'阅读者可以先了解工具解决什么问题、怎样开始使用，再沿着原文来源继续探索。此处展示摘要区域的文字层级。',source_name:'示例产品信源',source_id:'example-source-b',published:Date.now()-7200000,category:'ai-products',score1:78,score2:82,selected:1,reason:'当资料提供可复用的做法时，推荐理由会突出具体的使用价值。',tags:'["产品更新","Agent"]',url:'https://github.com/KKKKhazix/AIHOT'},
  {id:'example-3',title_zh:'示例：一篇研究，解释模型能力变化的原因',summary_zh:'摘要只依据当前资料，不补写未经原文支持的效果、因果或性能结论。研究内容也可以在分类中独立阅读。',source_name:'示例研究信源',source_id:'example-source-c',published:Date.now()-10800000,category:'paper',score1:80,score2:80,selected:1,reason:'介绍一项具体发现，帮助读者理解能力边界与实际影响。',tags:'["论文/研究","推理"]',url:'https://github.com/KKKKhazix/AIHOT'}
];
async function api(path) {
  const response=await fetch(API+path,{headers:{Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(15000)});
  if(!response.ok)throw Error('数据服务暂时不可用');
  if(!response.headers.get('content-type')?.includes('application/json'))throw Error('数据服务尚未接通');
  return response.json();
}
function relative(t){const hours=Math.max(0,Math.floor((Date.now()-Number(t))/3600000));return hours<1?'刚刚':hours<24?hours+' 小时前':new Date(Number(t)).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric'})}
function tagList(item){try {const a=JSON.parse(item.tags||'[]');return Array.isArray(a)?a.filter(t=>typeof t==='string').slice(0,6):[]}catch{return []}}
function card(item){const score=Number.isFinite(item.score1)&&Number.isFinite(item.score2)?Math.round((item.score1+item.score2)/2):null;return `<article class="news-card">
  <div class="news-meta"><span class="news-category">${esc(categories.find(c=>c.key===item.category)?.label||'动态')}</span><span>${esc(item.source_name)}</span><span>·</span><time datetime="${Number.isFinite(Number(item.published))?new Date(Number(item.published)).toISOString():''}">${relative(item.published)}</time></div>
  <button type="button" class="star-button ${stars[item.id]?'saved':''}" data-star="${esc(item.id)}" aria-label="${stars[item.id]?'取消收藏':'收藏'}：${esc(item.title_zh||item.title)}" aria-pressed="${Boolean(stars[item.id])}">${icon('star')}</button>
  <h3><a href="?item=${encodeURIComponent(item.id)}" data-item="${esc(item.id)}">${esc(item.title_zh||item.title)}</a></h3>
  <p class="news-summary">${esc(item.summary_zh)}</p>${item.selected&&item.reason?`<p class="news-reason">${esc(item.reason)}</p>`:''}
  <div class="news-tags">${tagList(item).map(t=>`<span># ${esc(t)}</span>`).join('')}</div>
  <div class="news-bottom"><span>${score!==null?`${item.selected?'精选':'阅读'}评分 ${score} · 两次独立评估`:'原文摘要'}</span><a href="${esc(safe(item.url))}" target="_blank" rel="noopener noreferrer">阅读原文 ${icon('arrow')}</a></div></article>`}
function renderItems(items,append=false){if(append)current.push(...items);else current=items;$('#articles').innerHTML=current.length?current.map(card).join(''):empty(view==='starred'?'还没有收藏的发现':'暂时没有符合条件的内容',view==='starred'?'点击文章右上角的星标，把想继续读的资料留在这里。':'新内容收录并处理后会显示在这里，也可以切换分类或清空搜索。');$('#result-count').textContent=current.length?current.length+' 条动态':'';updateStars()}
function empty(title,description,retry=false){return `<div class="empty-state"><h3>${esc(title)}</h3><p>${esc(description)}</p>${retry?'<button type="button" data-retry>重新连接</button>':''}</div>`}
function updateStars(){$('#star-count').textContent=Object.keys(stars).length;document.querySelectorAll('[data-star]').forEach(button=>{const saved=Boolean(stars[button.dataset.star]);button.classList.toggle('saved',saved);button.setAttribute('aria-pressed',String(saved));button.setAttribute('aria-label',(saved?'取消收藏':'收藏')+'：'+(stars[button.dataset.star]?.title_zh||current.find(i=>i.id===button.dataset.star)?.title_zh||'这条动态'))})}
function setView(next){if(!views[next])return;view=next;offset=0;category='all';query='';$('#categories').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.category==='all'));$('#query').value='';const u=new URL(location.href);u.searchParams.set('view',view);u.searchParams.delete('item');history.replaceState(null,'',u);refresh()}
async function refresh(append=false){const id=++requestId;document.querySelectorAll('#views button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});$('#view-kicker').textContent=views[view][0];$('#list-heading').textContent=views[view][1];$('#search-form').hidden=['hot','daily','sources'].includes(view);$('#categories').hidden=['hot','daily','sources'].includes(view);$('#more').hidden=true;$('#more').disabled=true;$('#notice').textContent=preview?'布局示例 · 正式上线时只展示已收录的真实内容':'';$('#result-count').textContent='';if(!append)$('#articles').innerHTML=empty('正在读取','稍等片刻，正在整理你关心的内容。');
  try {
    if(view==='starred'){const rows=Object.values(stars).filter(i=>(category==='all'||i.category===category)&&(!query||(i.title_zh+' '+i.summary_zh).toLowerCase().includes(query.toLowerCase())));renderItems(rows);return}
    if(view==='hot'){const data=preview?{events:mock.map((i,n)=>({id:i.id,title:i.title_zh,summary:i.summary_zh,sourceCount:3-n,items:[i]}))}:await api('/hot');if(id!==requestId)return;current=data.events.flatMap(e=>e.items);$('#articles').innerHTML=data.events.length?data.events.map((e,n)=>`<article class="news-card"><div class="news-meta"><span class="news-category">热点 ${String(n+1).padStart(2,'0')}</span><span>${e.sourceCount} 个独立来源</span></div><h3>${esc(e.title)}</h3><p class="news-summary">${esc(e.summary)}</p><div class="news-bottom"><span>48 小时内 · 来源越多，热度越高</span><a href="?item=${encodeURIComponent(e.items[0].id)}" data-item="${esc(e.items[0].id)}">查看报道 ${icon('arrow')}</a></div></article>`).join(''):empty('热点还在积累','收录到的相关报道会归为事件，按独立来源和时间计算热度。');return}
    if(view==='sources'){const data=preview?{sources:mock.map((i,n)=>({id:i.source_id,name:i.source_name,tier:'T1',enabled:1,url:i.url,last_success:null,error:null}))}:await api('/sources');if(id!==requestId)return;$('#articles').innerHTML=data.sources.map(s=>`<article class="news-card source-card"><div><h3><a href="${esc(safe(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a></h3><p>${s.tier==='T1'?'官方一手':'媒体与个人'} · RSS / Atom</p>${s.error?`<p class="article-error">暂未收录成功 · ${esc(s.error)}</p>`:''}</div><span class="source-state ${s.error?'error':''}">${!s.enabled?'已暂停':s.last_success?'正在关注':'等待首次收录'}</span></article>`).join('');$('#notice').textContent=preview?'示例信源，正式版使用 AIHOT 的 18 个公开示范源。':'保留原文版权，只提供摘要与原文链接。个别信源失效或限制访问时会显示状态。';return}
    if(view==='daily'){await renderReport(null,id);return}
    const params=new URLSearchParams({view,offset:String(offset)});if(category!=='all')params.set('category',category);if(query)params.set('q',query);
    const data=preview?{items:mock.filter(i=>(category==='all'||i.category===category)&&(!query||(i.title_zh+' '+i.summary_zh).includes(query))),hasMore:false}:await api('/items?'+params);
    if(id!==requestId)return;renderItems(data.items,append);$('#more').hidden=!data.hasMore;$('#more').disabled=false;
  }catch(error){if(id!==requestId)return;if(append){offset=Math.max(0,offset-30);$('#more').hidden=false;$('#more').disabled=false;$('#notice').textContent='加载失败，请再试一次';return}current=[];$('#articles').innerHTML=empty('暂时连接不到热点服务','请稍后重试。现有收藏仍可在“我的收藏”里阅读。',true);$('#notice').textContent=error.message;$('#service-state').textContent='服务未连接'}
}
async function renderReport(date,id){const data=preview?{report:{date:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),title:'示例早报：把值得看的变化，整理在一起',lead:'这是一段虚构导语。正式早报只依据已经入选的动态，把核心变化和阅读线索放在开头，帮助你快速进入今天的 AI 世界。',items:mock}}:await api('/report'+(date?'?date='+encodeURIComponent(date):''));if(id!==requestId)return;if(!data.report){$('#articles').innerHTML=empty('第一份早报，还在准备','已有精选后，每天北京时间 08:00 起生成；没有精选时不会拼凑空日报。');return}current=data.report.items;const archive=preview?{reports:[data.report]}:await api('/reports');if(id!==requestId)return;reportArchive=archive.reports;$('#articles').innerHTML=`<label class="sr-only" for="edition">选择早报日期</label><select class="report-picker" id="edition">${reportArchive.map(r=>`<option value="${esc(r.date)}" ${r.date===data.report.date?'selected':''}>${esc(r.date)} · ${esc(r.title)}</option>`).join('')}</select><section class="report-lead"><p class="eyebrow">SOFTCLOUD DAILY / ${esc(data.report.date)}</p><h3>${esc(data.report.title)}</h3><p>${esc(data.report.lead)}</p></section>${current.map(card).join('')}`;updateStars()}
async function openItem(id){let item=current.find(i=>i.id===id)||stars[id];if(!item&&!preview){try{item=(await api('/item/'+encodeURIComponent(id))).item}catch{$('#notice').textContent='这条内容暂时无法读取';return}}if(!item)return;const dialog=$('#detail');$('#detail-content').innerHTML=`<div class="news-meta"><span class="news-category">${esc(categories.find(c=>c.key===item.category)?.label||'动态')}</span><span>${esc(item.source_name)}</span></div><h2>${esc(item.title_zh||item.title)}</h2><p class="news-summary">${esc(item.summary_zh)}</p>${item.reason?`<p class="news-reason">${esc(item.reason)}</p>`:''}<div class="news-bottom"><span>${relative(item.published)} · 摘要由 AI 辅助整理</span><a href="${esc(safe(item.url))}" target="_blank" rel="noopener noreferrer">阅读完整原文 ${icon('arrow')}</a></div>`;if(!dialog.open)dialog.showModal();const u=new URL(location.href);u.searchParams.set('item',id);history.replaceState(null,'',u)}
function closeDetail(){$('#detail').close();const u=new URL(location.href);u.searchParams.delete('item');history.replaceState(null,'',u)}
document.addEventListener('click',event=>{const star=event.target.closest('[data-star]');if(star){const id=star.dataset.star;if(stars[id])delete stars[id];else{const item=current.find(i=>i.id===id);if(item)stars[id]=item}try{localStorage.setItem('softcloud-ai-hot-stars',JSON.stringify(stars));$('#notice').textContent='收藏已保存在当前浏览器'}catch{$('#notice').textContent='浏览器无法保存收藏，请保持当前页面'}if(view==='starred')renderItems(Object.values(stars));else updateStars();return}const item=event.target.closest('[data-item]');if(item){event.preventDefault();openItem(item.dataset.item);return}const nav=event.target.closest('[data-view]');if(nav)setView(nav.dataset.view);if(event.target.closest('[data-retry]')){offset=0;refresh();loadSide()}});
$('#categories').innerHTML=categories.map(c=>`<button type="button" data-category="${c.key}" class="${c.key===category?'active':''}">${c.label}</button>`).join('');
$('#categories').addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;category=button.dataset.category;offset=0;$('#categories').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));refresh()});
$('#search-form').addEventListener('submit',event=>{event.preventDefault();query=$('#query').value.trim();offset=0;refresh()});
$('#query').addEventListener('input',()=>{if(!$('#query').value&&query){query='';offset=0;refresh()}});
$('#more').addEventListener('click',()=>{if($('#more').disabled)return;offset+=30;refresh(true)});
$('#articles').addEventListener('change',event=>{if(event.target.id==='edition')renderReport(event.target.value,++requestId)});
$('.dialog-close').addEventListener('click',closeDetail);$('#detail').addEventListener('cancel',event=>{event.preventDefault();closeDetail()});
$('#theme').addEventListener('click',()=>{const html=document.documentElement;html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('softcloud-theme-blue',html.dataset.theme)}catch{}themeLabel()});
function themeLabel(){$('#theme').setAttribute('aria-label',document.documentElement.dataset.theme==='dark'?'切换浅色主题':'切换深色主题')}
async function loadSide(){if(preview){$('#hot-preview').innerHTML=mock.map((i,n)=>`<div class="hot-mini"><span class="hot-rank">${String(n+1).padStart(2,'0')}</span><div><p>${esc(i.title_zh)}</p><small>${3-n} 个示例来源</small></div></div>`).join('');$('#service-state').textContent='界面示例';return}const results=await Promise.allSettled([api('/status'),api('/hot'),api('/report')]);if(results[0].status==='fulfilled'){const s=results[0].value;$('#service-state').textContent=s.paused?'今日额度已用完':s.modelEnabled?(s.collecting?'正在持续收录':'收录已暂停'):'等待启用';if(s.paused)$('#notice').textContent='今日处理已暂停，已有内容仍可阅读。'}else $('#service-state').textContent='服务未连接';if(results[1].status==='fulfilled'){$('#hot-preview').innerHTML=results[1].value.events.slice(0,3).map((e,n)=>`<a href="?item=${encodeURIComponent(e.items[0].id)}" class="hot-mini" data-item="${esc(e.items[0].id)}"><span class="hot-rank">${String(n+1).padStart(2,'0')}</span><div><p>${esc(e.title)}</p><small>${e.sourceCount} 个独立来源</small></div></a>`).join('')||'<p class="side-empty">热点还在积累，每条报道都会保留原文来源。</p>'}else $('#hot-preview').innerHTML='<p class="side-empty">暂时无法读取热点。</p>';if(results[2].status==='fulfilled'&&results[2].value.report)$('#report-preview').textContent=results[2].value.report.date+' · '+results[2].value.report.title}
$('#date-label').textContent=new Date().toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'long'});$('#preview-banner').hidden=!preview;themeLabel();updateStars();const initialItem=new URLSearchParams(location.search).get('item');await refresh();loadSide();if(initialItem)openItem(initialItem);
