import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker,{parseFeed} from '../dist-test/worker.mjs';
import {eventHeat, isSelected, neuronReservation, reportWindow, archiveItem} from '../src/core.mjs';

class DB {
  constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'))}
  prepare(sql){const db=this.sqlite;let args=[];const p={bind(...v){args=v;return p},async run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}}},async first(){return db.prepare(sql).get(...args)||null},async all(){return{results:db.prepare(sql).all(...args)}}};return p}
  async batch(statements){this.sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.sqlite.exec('COMMIT');return results}catch(e){this.sqlite.exec('ROLLBACK');throw e}}
}
function environment(results=[]){const db=new DB();const jobs=[];const prompts=[];const env={DB:db,JOBS:{async send(job){jobs.push(job)}},AI:{async run(model,input){prompts.push(JSON.stringify(input.messages));assert.equal(input.response_format.type,'json_schema');assert.equal(input.messages[0].role,'system');assert.ok(input.messages[1].content.endsWith('/no_think'));const result=results.shift();if(result instanceof Error)throw result;if(!result)throw Error('unexpected model call');return{response:JSON.stringify(result)}}},COLLECT_ENABLED:'false',MODEL_CALLS_ENABLED:'true',FREE_PLAN_VERIFIED:'true',DAILY_NEURON_BUDGET:'6000',DAILY_ARTICLE_LIMIT:'24',SITE_URL:'https://zoci.pro/tools/ai-hot/'};return{env,db,jobs,prompts}}
async function addItem(db,overrides={}){await db.prepare('INSERT INTO sources(id,name,url,tier) VALUES(?,?,?,?)').bind('source','Official source','https://example.com/feed','T1').run();const row={id:'0123456789abcdef01234567',url:'https://example.com/news',title:'Release of a test AI model',body:'A test AI model is available in a public API. This fixture is not real news.',published:Date.now()-3600000,discovered:Date.now(),...overrides};await db.prepare('INSERT INTO items(id,source_id,url,title,body,published,discovered,stage) VALUES(?,?,?,?,?,?,?,?)').bind(row.id,'source',row.url,row.title,row.body,row.published,row.discovered,row.stage||'prefilter').run();return row}
async function consume(env,job){let ack=false,retry=false;await worker.queue({messages:[{body:job,attempts:1,ack(){ack=true},retry(){retry=true}}]},env);assert.equal(retry,false);assert.equal(ack,true)}
globalThis.caches={default:{async match(){return undefined},async put(){}}};
const ctx={waitUntil(p){p.catch(()=>{})}};
const get=(env,path,options)=>worker.fetch(new Request('https://zoci.pro/api/ai-hot'+path,options),env,ctx);

test('RSS and Atom keep HTTPS sources and reject script links',()=>{const rss=parseFeed('<rss><channel><item><title>A &amp; B</title><link>https://example.com/a</link><description><![CDATA[<p>A useful summary</p>]]></description><pubDate>Tue, 29 Sep 2026 01:00:00 GMT</pubDate></item><item><title>Unsafe</title><link>javascript:alert(1)</link></item></channel></rss>');assert.equal(rss.length,1);assert.equal(rss[0].title,'A & B');assert.equal(rss[0].body,'A useful summary');const atom=parseFeed('<feed><entry><title>Atom</title><link rel="self" href="https://example.com/raw"/><link rel="alternate" href="https://example.com/article"/><summary>Hello</summary></entry></feed>');assert.equal(atom[0].url,'https://example.com/article')});
test('two scores use exact thresholds without rounding into selection',()=>{assert.equal(isSelected(59,60,60),false);assert.equal(isSelected(59,61,60),true);assert.equal(isSelected(75,76,76),false);assert.equal(isSelected(null,80,60),false);assert.equal(isSelected(90,90,undefined),false)});
test('repeat publications from one source never inflate event heat',()=>{const now=Date.now();assert.equal(eventHeat([{source_id:'a',published:now},{source_id:'a',published:now}],now),1);assert.equal(eventHeat([{source_id:'a',published:now},{source_id:'b',published:now-86400000}],now),1.5);assert.equal(eventHeat([{source_id:'a',published:now,archived:1}],now),0)});
test('old content and morning report use actual publish time in Beijing',()=>{const now=Date.now();assert.equal(archiveItem(now-49*3600000,now),true);const w=reportWindow('2026-09-30');assert.equal(new Date(w.end).toISOString(),'2026-09-30T00:00:00.000Z');assert.equal(w.end-w.start,86400000)});
test('the pipeline publishes only after prefilter, independent scores and summary',async()=>{const e=environment([{label:'PASS'},{attentionScore:60},{attentionScore:64},{itemType:'model_release',tags:['模型发布','推理'],titleZh:'用于测试的模型发布',summaryZh:'这是本地测试资料的摘要。',editorialJudgment:'这段资料说明了模型的开放入口。'}]);const row=await addItem(e.db);for(let n=0;n<5;n++){await consume(e.env,{kind:'item',id:row.id});const publicData=await(await get(e.env,'/items')).json();if(n<4)assert.equal(publicData.items.length,0)}assert.equal(e.prompts.length,4);assert.equal(e.prompts[1],e.prompts[2]);const data=await(await get(e.env,'/items?view=selected')).json();assert.equal(data.items.length,1);assert.equal(data.items[0].selected,1);assert.equal(data.items[0].body,undefined);await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,4)});
test('budget is reserved atomically and exhausted budget makes no model call',async()=>{const e=environment([{label:'PASS'}]);const row=await addItem(e.db);e.env.DAILY_NEURON_BUDGET='1';await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,0);assert.equal((await e.db.prepare('SELECT stage FROM items').first()).stage,'prefilter');assert.equal((await e.db.prepare('SELECT reserved FROM budgets').first()).reserved,0);assert.ok(neuronReservation('中文摘要',100)>1)});
test('Cloudflare quota failure blocks further calls for that UTC day',async()=>{const e=environment([Error('Workers AI neurons quota exceeded')]);const row=await addItem(e.db);await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,1);await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,1);assert.equal((await e.db.prepare('SELECT blocked FROM budgets').first()).blocked,1)});
test('completed receipts are reused after a stage write fails',async()=>{const e=environment([{label:'PASS'}]);const row=await addItem(e.db);await consume(e.env,{kind:'item',id:row.id});await e.db.prepare("UPDATE items SET stage='prefilter'").run();await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,1)});
test('UNKNOWN stays pending for review and never becomes public',async()=>{const e=environment([{label:'UNKNOWN'}]);const row=await addItem(e.db);await consume(e.env,{kind:'item',id:row.id});assert.equal((await e.db.prepare('SELECT stage FROM items').first()).stage,'unknown');assert.equal((await(await get(e.env,'/items')).json()).items.length,0)});
test('disabled AI and an unverified free plan never invoke the model',async()=>{for(const key of ['MODEL_CALLS_ENABLED','FREE_PLAN_VERIFIED']){const e=environment([{label:'PASS'}]);const row=await addItem(e.db);e.env[key]='false';await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,0)}});
test('admin requires a configured token and public API rejects writes',async()=>{const e=environment();assert.equal((await get(e.env,'/admin')).status,401);e.env.ADMIN_TOKEN='test-only-admin-token-123456789';assert.equal((await get(e.env,'/admin',{headers:{Authorization:'Bearer wrong'}})).status,401);assert.equal((await get(e.env,'/admin',{headers:{Authorization:'Bearer '+e.env.ADMIN_TOKEN}})).status,200);assert.equal((await get(e.env,'/items',{method:'POST'})).status,405)});
test('search treats percent and underscore literally',async()=>{const e=environment();await addItem(e.db,{stage:'done'});await e.db.prepare("UPDATE items SET title_zh='AI 100% test',summary_zh='a_b'").run();assert.equal((await(await get(e.env,'/items?q=%25')).json()).items.length,1);assert.equal((await(await get(e.env,'/items?q=no%25')).json()).items.length,0)});

test('daily article cap also blocks a queued new article',async()=>{const e=environment([{label:'PASS'}]);const row=await addItem(e.db);e.env.DAILY_ARTICLE_LIMIT='0';await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,0);assert.equal((await e.db.prepare('SELECT reserved FROM budgets').first()).reserved,0)});

test('protocol recovery preserves old receipts and counts the same article once',async()=>{const e=environment([{label:'PASS'}]);const row=await addItem(e.db,{stage:'failed'});const oldId=row.id+':prefilter';const day=new Date().toISOString().slice(0,10);await e.db.prepare("INSERT INTO receipts(id,day,reserved,state,result,error) VALUES(?,?,7,'error',?,?)").bind(oldId,day,JSON.stringify({response:'invalid completion'}),'invalid JSON').run();await e.db.prepare('INSERT INTO budgets(day,reserved) VALUES(?,7)').bind(day).run();e.db.sqlite.exec(readFileSync(new URL('../migrations/0002_chat_protocol_recovery.sql',import.meta.url),'utf8'));e.env.DAILY_ARTICLE_LIMIT='1';await consume(e.env,{kind:'item',id:row.id});assert.equal((await e.db.prepare('SELECT stage FROM items').first()).stage,'score1');assert.equal(e.prompts.length,1);assert.equal((await e.db.prepare('SELECT result FROM receipts WHERE id=?').bind(oldId).first()).result,JSON.stringify({response:'invalid completion'}));assert.ok((await e.db.prepare('SELECT reserved FROM budgets').first()).reserved>7);await e.db.prepare("UPDATE items SET stage='prefilter'").run();await consume(e.env,{kind:'item',id:row.id});assert.equal(e.prompts.length,1)});
