import {query,one,iso} from './publication.ts';
type Row=Record<string,any>;
export async function contentChain(db:D1Database,id:string) {
 const a=await one<Row>(db,'SELECT i.*,s.name source_name,s.kind source_kind,s.tier,s.participation_mode,s.first_party FROM items i JOIN sources s ON s.id=i.source_id WHERE i.id=?',id);if(!a)return null;
 const receipts=await query<Row>(db,'SELECT * FROM receipts WHERE substr(id,1,24)=? ORDER BY created,id',id);
 const override=await one<Row>(db,'SELECT * FROM item_overrides WHERE item_id=?',id);
 const membership=await query<Row>(db,'SELECT e.id fact_id,e.title fact_title,e.story_id,st.id story_public_id,st.title story_title FROM events e JOIN stories st ON st.id=e.story_id WHERE e.id=?',a.event_id);
 const history=await query<Row>(db,'SELECT * FROM admin_audit WHERE subject=? ORDER BY id DESC LIMIT 50','content:'+id);
 const ledger=await query<Row>(db,'SELECT seq,op,changed FROM selected_ledger WHERE item_id=? ORDER BY seq DESC LIMIT 50',id);
 return {article:{...a,processing_state:a.stage,processing_error:a.error,timeline_at:iso(a.published),discovered_at:iso(a.discovered),published_at:iso(a.published),site_fulltext:false,syndicate_fulltext:false,backfill:Boolean(a.archived),body_status:a.body?'feed':'summary-retained',body_chars:a.body.length},discoveries:[{source_id:a.source_id,via:'RSS/Atom',discovered_at:iso(a.discovered)}],revisions:[],analyses:receipts.filter(r=>r.purpose==='understand').map(r=>({id:r.id,relevance:'pass',score:(a.score1+a.score2)/2,title_zh:a.title_zh,reason_zh:a.reason,category:a.category,model:r.model,prompt_version:'upstream-885b736',input_revision:a.revision,origin:'Workers AI',created_at:iso(r.created??a.discovered),receipts:receipts.map(x=>({...x,status:x.state,cost:null}))})),publication:a.stage==='done'?{title:a.title_zh??a.title,summary:a.summary_zh,reason:a.reason,selected:Boolean(a.selected),visibility:a.visibility,tags:JSON.parse(a.tags),category:a.category,body_mode:'summary-only',syndicate:false,indexable:Boolean(a.indexable),updated_at:iso(a.updated||a.discovered)}:null,override:override?{...override,fields:JSON.parse(override.fields),visibility:a.visibility,updated_by:'管理员',updated_at:iso(override.updated)}:null,ledger:ledger.map(r=>({...r,changed_at:iso(r.changed),visible_at:iso(r.changed)})),membership:membership.map(m=>({...m,role:'report',manual:false})),decisions:[],deliveries:[],history:history.map(h=>({...h,actor:'管理员',created_at:iso(h.created),before:JSON.parse(h.before_value),after:JSON.parse(h.after_value)}))};
}
export async function runView(db:D1Database) {
 const runs=await query<Row>(db,'SELECT * FROM runs ORDER BY created DESC LIMIT 100');
 const pending=await query<Row>(db,"SELECT stage,count(*) n,min(discovered) oldest FROM items WHERE stage NOT IN ('done','unknown','blocked') GROUP BY stage");
 const errors=await query<Row>(db,"SELECT i.id,i.stage state,i.error processing_error,i.next_attempt,s.name source_name FROM items i JOIN sources s ON s.id=i.source_id WHERE i.error IS NOT NULL ORDER BY i.discovered DESC LIMIT 50");
 const receipts=await query<Row>(db,'SELECT * FROM receipts WHERE created>? OR created IS NULL ORDER BY created DESC LIMIT 500',Date.now()-7*86400000);
 const counts:Record<string,number>={};for(const r of receipts)counts[r.state]=(counts[r.state]??0)+1;
 const lagging=await query<Row>(db,'SELECT * FROM sources WHERE enabled=1 AND (error IS NOT NULL OR last_checked+interval_minutes*60000<?)',Date.now());
 const latest=runs.find(r=>r.kind==='scheduled');
 return {checkedAt:iso(Date.now()),processes:latest?[{role:'worker',pid:0,host:'Cloudflare Cron',release:'softcloud-ai-hot',startedAt:iso(latest.created),at:iso(latest.created),alive:latest.status==='ok'&&Date.now()-latest.created<1800000}]:[],jobs:[...new Set(runs.map(r=>r.kind))].map(job=>{const group=runs.filter(r=>r.kind===job);const latest=group[0];return {job,status:latest.status==='error'?'failed':latest.status,started_at:iso(latest.created),finished_at:null,error:latest.status==='error'?latest.message:null,failed_24h:group.filter(r=>r.status==='error'&&r.created>Date.now()-86400000).length,runs_24h:group.filter(r=>r.created>Date.now()-86400000).length};}),timeline:runs.map(r=>({...r,name:r.kind,job:r.kind,started_at:iso(r.created),finished_at:null,error:r.status==='error'?r.message:null})),queues:pending.map(p=>({name:'内容待处理（D1）',state:p.stage==='failed'?'retry':'created',n:p.n,oldest:iso(p.oldest)})),failedJobs:[],lagging:lagging.map(s=>({...s,health:s.error?'failing':'degraded',last_ok_at:s.last_success?iso(s.last_success):null,next_fetch_at:iso(s.last_checked+s.interval_minutes*60000)})),receipts:{counts,issues:receipts.filter(r=>r.state==='error').map(r=>({...r,status:r.state,service:'Workers AI',subject:r.id.slice(0,24)}))},deliveries:[],errors:errors.map(e=>({...e,processing_state:e.state,next_attempt_at:e.next_attempt?iso(e.next_attempt):null})),retrying:{count:errors.filter(e=>e.next_attempt>Date.now()).length,next:errors.filter(e=>e.next_attempt>Date.now()).length?iso(Math.min(...errors.filter(e=>e.next_attempt>Date.now()).map(e=>e.next_attempt))):null},ingest:[],leaderboard:null};
}
export function bench(row:Row) {
 const report=JSON.parse(row.report),models=report.models??Object.fromEntries(Object.entries(report).filter(([k])=>k!=='meta')),names=Object.keys(models),meta=report.meta??{};
 const byCase=new Map<string,Row>();
 for(const model of names)for(const c of models[model].cases??[]){const key=String(c.caseId);const current=byCase.get(key)??{case_id:key,title:c.title,stratum:c.stratum??null,gold:c.gold,by_model:{}};current.by_model[model]={...c};byCase.set(key,current);}
 const rows=[...byCase.values()];const strata=[...new Set(rows.map(r=>r.stratum))].map(stratum=>({stratum,n:rows.filter(r=>r.stratum===stratum).length}));
 return {run:{id:row.id,label:row.label,split:meta.split??null,sample_size:Number(meta.n??models[names[0]]?.summary.n??0),prompt_version:meta.promptVersion??null,models:names,summary:Object.fromEntries(names.map(m=>[m,models[m].summary])),created_at:iso(row.created),imported_by:'管理员',cases:rows.length},rows,strata};
}
