// 主题系统：少而精，每套主题对应一种内容定位（tag），结构与气质完全不同。
// mock 字段用于主题画廊里的缩略图造型。
//
// 公众号安全区（已实测 + 资料验证）：内联样式、渐变（配纯色兜底）、box-shadow、
// border-radius、letter-spacing、flex。禁区：position 定位、<style>、动画、百分比偏移。
// 本文件的设计全部落在安全区内。
//
// 标题等尺寸全部使用 em，正文字号变化时整体等比缩放。

const FONT_STACKS = {
  sans: `-apple-system-font,BlinkMacSystemFont,'Helvetica Neue','PingFang SC','Hiragino Sans GB','Microsoft YaHei',Arial,sans-serif`,
  serif: `Georgia,'Times New Roman','Songti SC','STSong','SimSun',serif`,
  rounded: `'Yuanti SC','YouYuan','PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif`,
}

export const fontOptions = [
  { id: 'theme', name: '跟随主题' },
  { id: 'sans', name: '黑体' },
  { id: 'serif', name: '宋体' },
  { id: 'rounded', name: '圆体' },
]

// 基础样式：为主题未单独覆盖的组件提供稳定兜底。
const baseStyles = (p, fs, font) => ({
  container: `font-family:${font};font-size:${fs}px;line-height:1.8;color:#3f3f46;letter-spacing:0.02em;padding:0 8px;word-break:break-word;overflow-wrap:anywhere;`,
  h1: `font-size:1.4em;font-weight:700;text-align:center;color:${p};margin:1.5em 8px 0.9em;line-height:1.4;letter-spacing:0.02em;`,
  h2: `font-size:1.2em;font-weight:700;color:#18181b;margin:1.8em 8px 0.9em;padding-left:0.55em;border-left:5px solid ${p};line-height:1.45;`,
  h2WrapOpen: '',
  h2WrapClose: '',
  h3: `font-size:1.1em;font-weight:700;color:#18181b;margin:1.6em 8px 0.7em;padding-left:0.5em;border-left:3px solid ${p};line-height:1.45;`,
  h4: `font-size:1em;font-weight:700;color:${p};margin:1.4em 8px 0.6em;line-height:1.45;`,
  h5: `font-size:0.94em;font-weight:700;color:#3f3f46;margin:1.3em 8px 0.55em;line-height:1.5;`,
  h6: `font-size:0.86em;font-weight:700;color:#71717a;margin:1.2em 8px 0.5em;line-height:1.5;letter-spacing:0.05em;`,
  p: `margin:0 8px 1.3em;`,
  liP: `margin:0 0 0.4em;text-align:left;text-indent:0;`,
  blockquote: `margin:1.5em 8px;padding:0.8em 1em;background-color:#f4f4f5;border-left:4px solid ${p};border-radius:0 8px 8px 0;color:#52525b;font-size:0.94em;`,
  bqP: `margin:0;text-indent:0;`,
  ul: `margin:0.8em 8px 1.3em;padding-left:1.5em;text-align:left;text-indent:0;list-style-position:outside;`,
  ol: `margin:0.8em 8px 1.3em;padding-left:1.5em;text-align:left;text-indent:0;list-style-position:outside;`,
  li: `margin:0.4em 0;text-align:left;text-indent:0;`,
  a: `color:${p};text-decoration:none;border-bottom:1px solid ${p};padding-bottom:1px;`,
  strong: `font-weight:700;color:${p};`,
  em: `font-style:italic;color:#52525b;`,
  s: `color:#a1a1aa;text-decoration-thickness:1px;`,
  mark: `background-color:${p}26;padding:0 2px;border-radius:3px;`,
  img: `display:block;max-width:100%;margin:1.2em auto;border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,0.08);`,
  gallery: `margin:1.3em 8px;`,
  galleryImg: `display:block;width:100%;margin:0;border-radius:6px;`,
  video: `margin:1.6em 8px;padding:1.3em 1em;border:2px dashed ${p};border-radius:12px;text-align:center;color:${p};line-height:1.6;`,
  caption: `display:block;text-align:center;font-size:0.78em;color:#a1a1aa;margin:-0.5em 0 1.2em;letter-spacing:0.04em;`,
  hr: `border:none;border-top:1px solid #e4e4e7;margin:2em 16px;`,
  code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f2f3f5;color:#c0341d;padding:2px 6px;border-radius:5px;`,
  tableWrap: `overflow-x:auto;margin:1.2em 8px;`,
  table: `width:100%;border-collapse:collapse;font-size:0.9em;`,
  th: `border:1px solid #e4e4e7;padding:8px 12px;background-color:${p}14;font-weight:700;text-align:left;`,
  td: `border:1px solid #e4e4e7;padding:8px 12px;`,
})

export const themes = [
  {
    id: 'literary',
    name: '纸上散文',
    tag: '人文 · 随笔',
    description: '宋体书页与舒展行距，为散文、书评保留安静的呼吸。',
    primary: '#9c4b3f',
    font: 'serif',
    fontLocked: true,
    mock: 'lines',
    surface: '#ffffff',
    previewFade: '#ffffff',
    styles: (p) => ({
      // 现代文艺：宋体书页、两侧长划线标题、居中拉页引用
      h1: `font-size:1.5em;font-weight:600;text-align:center;color:#3a3630;margin:1.6em 8px 1em;letter-spacing:0.2em;line-height:1.6;`,
      h2: `font-size:1.15em;font-weight:600;text-align:center;color:#3a3630;margin:2em 8px 1em;letter-spacing:0.12em;line-height:1.6;`,
      h2WrapOpen: `<span style="color:#b8ab8e;margin-right:0.6em;font-weight:400;">—</span>`,
      h2WrapClose: `<span style="color:#b8ab8e;margin-left:0.6em;font-weight:400;">—</span>`,
      h3: `font-size:1.05em;font-weight:600;color:#3a3630;margin:1.8em 8px 0.7em;letter-spacing:0.08em;line-height:1.6;`,
      h4: `font-size:1em;font-weight:600;color:${p};margin:1.5em 8px 0.6em;letter-spacing:0.06em;line-height:1.6;`,
      h5: `font-size:0.94em;font-weight:600;color:#6d6458;margin:1.4em 8px 0.55em;letter-spacing:0.05em;line-height:1.6;`,
      h6: `font-size:0.86em;font-weight:600;color:#9a8e7c;margin:1.3em 8px 0.5em;letter-spacing:0.08em;line-height:1.6;`,
      p: `margin:0 8px 1.3em;text-indent:2em;text-align:left;line-height:2;`,
      blockquote: `margin:1.8em 20px;padding:0;color:#8a7f6a;font-size:1.02em;letter-spacing:0.06em;line-height:2;`,
      bqP: `margin:0;text-align:center;text-indent:0;`,
      strong: `font-weight:700;color:${p};`,
      em: `font-style:italic;color:#5f574d;`,
      s: `color:#a89c87;text-decoration-color:#b8ab8e;text-decoration-thickness:1px;`,
      a: `color:${p};text-decoration:none;border-bottom:1px dashed ${p};`,
      img: `display:block;max-width:100%;margin:1.4em auto;padding:4px;border:1px solid #e5ddcc;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a89c87;margin:-0.4em 0 1.2em;letter-spacing:0.08em;`,
      hrHtml: `<p style="text-align:center;color:#b8ab8e;margin:2.2em 0;letter-spacing:0.5em;">· · ·</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f5f1e8;color:${p};padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #e5ddcc;padding:8px 12px;background-color:#faf7ef;font-weight:600;text-align:left;`,
      td: `border:1px solid #e5ddcc;padding:8px 12px;`,
    }),
  },
  {
    id: 'swiss-index',
    name: '瑞士索引',
    tag: '理性 · 方法',
    description: '黑白网格、信号红与巨型编号，把教程和观点组织成清晰索引。',
    primary: '#e00019',
    font: 'sans',
    fontLocked: true,
    mock: 'index',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'label',
    codeLabel: 'CODE',
    extractH2Index: true,
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.78;color:#111111;letter-spacing:0;padding:12px 14px 26px;background-color:#ffffff;word-break:break-word;box-sizing:border-box;min-height:100%;`,
      h1: `font-size:2.3em;font-weight:900;text-align:left;color:#050505;margin:0.8em 8px 0.55em;padding:0 0 0.42em;border-bottom:2px solid #0a0a0a;line-height:1.08;letter-spacing:-0.045em;`,
      h1WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.25em;font-weight:800;line-height:1.2;letter-spacing:0.1em;margin-bottom:1.4em;">SWISS INDEX / 01</span>`,
      h2: `display:flex;align-items:flex-start;gap:0.72em;font-size:1.38em;font-weight:850;text-align:left;color:#0a0a0a;margin:2.15em 8px 0.85em;padding:0.65em 0 0;border-top:1px solid #111111;line-height:1.2;letter-spacing:-0.02em;`,
      h2Index: `flex:0 0 auto;color:#050505;font-size:2.35em;font-weight:900;line-height:0.78;letter-spacing:-0.08em;`,
      h2WrapOpen: `<span style="display:block;min-width:0;flex:1;"><span style="display:block;color:${p};font-size:0.42em;font-weight:800;letter-spacing:0.1em;margin-bottom:0.6em;">INDEX / SECTION</span>`,
      h2WrapClose: `</span>`,
      h3: `font-size:1.08em;font-weight:800;color:#111111;margin:1.7em 8px 0.65em;padding-left:0.72em;border-left:5px solid ${p};line-height:1.35;letter-spacing:-0.01em;`,
      h4: `font-size:0.96em;font-weight:800;color:${p};margin:1.45em 8px 0.55em;line-height:1.4;letter-spacing:0.04em;text-transform:uppercase;`,
      h5: `font-size:0.9em;font-weight:750;color:#111111;margin:1.35em 8px 0.5em;line-height:1.45;letter-spacing:0.03em;`,
      h6: `font-size:0.78em;font-weight:750;color:#686868;margin:1.25em 8px 0.45em;line-height:1.45;letter-spacing:0.1em;text-transform:uppercase;`,
      p: `margin:0 8px 1.18em;line-height:1.82;text-align:left;`,
      liP: `margin:0 0 0.35em;line-height:1.68;`,
      blockquote: `margin:1.65em 8px;padding:0.2em 0 0.2em 1em;background-color:transparent;border-left:3px solid ${p};border-radius:0;color:#333333;font-size:0.94em;line-height:1.75;`,
      bqP: `margin:0;`,
      ul: `margin:0.85em 8px 1.35em;padding-left:1.45em;list-style-type:square;`,
      ol: `margin:0.85em 8px 1.35em;padding-left:1.75em;list-style-type:decimal-leading-zero;`,
      li: `margin:0.48em 0;padding-left:0.25em;`,
      a: `color:#111111;text-decoration:none;border-bottom:2px solid ${p};padding-bottom:1px;`,
      strong: `font-weight:850;color:#050505;text-decoration:underline;text-decoration-color:${p};text-decoration-thickness:2px;text-underline-offset:2px;`,
      em: `font-style:italic;color:#333333;`,
      s: `color:#8c8c8c;text-decoration-color:${p};text-decoration-thickness:1px;`,
      mark: `background-color:${p};color:#ffffff;padding:1px 4px;border-radius:0;`,
      img: `display:block;max-width:100%;margin:1.35em auto;border-radius:0;box-shadow:none;`,
      gallery: `margin:1.45em 8px;padding-top:6px;border-top:1px solid #111111;`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:0;`,
      caption: `display:block;text-align:left;font-size:0.7em;color:#666666;margin:-0.55em 0 1.35em;padding-top:0.5em;border-top:1px solid #d8d8d8;letter-spacing:0.04em;`,
      hr: `border:none;border-top:2px solid #111111;margin:2.2em 8px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.82em;background-color:#eeeeee;color:#111111;padding:2px 5px;border-radius:0;border-bottom:2px solid ${p};`,
      tableWrap: `overflow-x:auto;margin:1.45em 8px;border-top:2px solid #111111;border-bottom:1px solid #111111;`,
      table: `width:100%;min-width:520px;border-collapse:collapse;font-size:0.82em;line-height:1.45;`,
      th: `border:none;border-bottom:1px solid #111111;padding:9px 8px 7px;background-color:transparent;color:#111111;font-weight:800;text-align:left;`,
      td: `border:none;border-bottom:1px solid #d8d8d8;padding:8px;color:#222222;`,
      pre: `background-color:#f1f1f1;border:1px solid #d8d8d8;border-radius:0;margin:1.45em 8px;overflow:hidden;`,
      preHeader: `padding:8px 12px;border-bottom:1px solid #d1d1d1;font-size:0;line-height:0;background-color:#ffffff;`,
      preLabel: `color:${p};font-size:10px;font-weight:800;line-height:12px;margin:0;letter-spacing:0.12em;vertical-align:top;`,
      preBody: `background-color:#f1f1f1;padding:13px 14px 15px;margin:0;overflow-x:auto;`,
      preCode: `color:#1b1b1b;`,
    }),
  },
  {
    id: 'night-film',
    name: '夜航胶片',
    tag: '影像 · 纪实',
    description: '午夜蓝、场记时间码与故事板图库，为城市观察和影像叙事定调。',
    primary: '#ff7a2d',
    font: 'sans',
    fontLocked: true,
    mock: 'film',
    surface: '#07111f',
    previewFade: '#07111f',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'TIMECODE',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.82;color:#c6cbd2;letter-spacing:0.015em;padding:16px 14px 30px;background-color:#07111f;word-break:break-word;box-sizing:border-box;min-height:100%;`,
      h1: `font-size:2em;font-weight:800;text-align:left;color:#fff0d7;margin:0.65em 8px 0.7em;padding:0 0 0.55em;border-bottom:5px solid ${p};line-height:1.18;letter-spacing:0.015em;`,
      h1WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.28em;font-weight:700;line-height:1.2;letter-spacing:0.1em;margin-bottom:1.35em;">DOCU-ESSAY / NIGHT FILM LOG</span>`,
      h2: `font-size:1.22em;font-weight:750;text-align:left;color:#f7ead6;margin:2.1em 8px 0.8em;padding:0.62em 0 0;border-top:1px dashed #415166;line-height:1.35;letter-spacing:0.02em;`,
      h2WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.48em;font-weight:700;letter-spacing:0.08em;margin-bottom:0.65em;">SCENE / 00:12:47:08</span>`,
      h3: `font-size:1.03em;font-weight:750;color:#f7ead6;margin:1.65em 8px 0.65em;padding-left:0.75em;border-left:3px solid ${p};line-height:1.45;`,
      h4: `font-family:Menlo,Consolas,monospace;font-size:0.84em;font-weight:700;color:${p};margin:1.5em 8px 0.55em;line-height:1.45;letter-spacing:0.08em;text-transform:uppercase;`,
      h5: `font-size:0.9em;font-weight:700;color:#e1e5e9;margin:1.35em 8px 0.5em;line-height:1.5;`,
      h6: `font-family:Menlo,Consolas,monospace;font-size:0.74em;font-weight:600;color:#718096;margin:1.25em 8px 0.45em;line-height:1.5;letter-spacing:0.1em;`,
      p: `margin:0 8px 1.25em;color:#c6cbd2;line-height:1.88;`,
      liP: `margin:0 0 0.35em;line-height:1.75;`,
      blockquote: `margin:1.6em 8px;padding:0.9em 1em;background-color:#0b1828;border-left:4px solid #314d70;border-radius:0;color:#f0e8db;font-size:0.94em;line-height:1.75;`,
      bqP: `margin:0;`,
      ul: `margin:0.85em 8px 1.35em;padding-left:1.5em;list-style-type:square;color:#d7dce2;`,
      ol: `margin:0.85em 8px 1.35em;padding-left:1.75em;color:#d7dce2;`,
      li: `margin:0.48em 0;padding-left:0.2em;`,
      a: `color:${p};text-decoration:none;border-bottom:1px solid ${p};padding-bottom:1px;`,
      strong: `font-weight:800;color:#fff0d7;`,
      em: `font-style:italic;color:#9cb2cb;`,
      s: `color:#667487;text-decoration-color:#8a3f39;text-decoration-thickness:1px;`,
      mark: `background-color:${p};color:#07111f;padding:1px 4px;border-radius:0;`,
      img: `display:block;max-width:100%;margin:1.35em auto;border:1px solid #2e3c4d;border-radius:0;box-shadow:none;`,
      gallery: `margin:1.45em 8px;padding:6px;border:1px solid #2e3c4d;background-color:#040b14;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #18283b;border-radius:0;box-sizing:border-box;`,
      caption: `display:block;text-align:left;font-family:Menlo,Consolas,monospace;font-size:0.68em;color:#77869a;margin:-0.55em 0 1.35em;letter-spacing:0.03em;`,
      hr: `border:none;border-top:1px dashed #415166;margin:2em 8px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.82em;background-color:#111f31;color:${p};padding:2px 6px;border-radius:0;`,
      tableWrap: `overflow-x:auto;margin:1.45em 8px;border:1px solid #5d5141;`,
      table: `width:100%;min-width:540px;border-collapse:collapse;font-family:Menlo,Consolas,monospace;font-size:0.78em;line-height:1.5;`,
      th: `border:1px solid #5d5141;padding:8px;background-color:#0a1523;color:#f3e6d2;font-weight:700;text-align:left;`,
      td: `border:1px solid #344153;padding:8px;color:#c6cbd2;`,
      pre: `background-color:#030912;border:1px solid #2a394c;border-radius:0;margin:1.45em 8px;overflow:hidden;`,
      preHeader: `padding:8px 12px;border-bottom:1px solid #2a394c;font-size:0;line-height:0;background-color:#07111f;`,
      preLabel: `color:${p};font-size:10px;font-weight:700;line-height:12px;margin:0;letter-spacing:0.1em;vertical-align:top;`,
      preBody: `background-color:#030912;padding:13px 14px 15px;margin:0;overflow-x:auto;`,
      preCode: `color:#c6cbd2;`,
    }),
  },
  {
    id: 'white-cube',
    name: '白盒展签',
    tag: '艺术 · 策展',
    description: '克莱因蓝馆藏编号与开放留白，适合作品、研究和设计档案。',
    primary: '#143bd1',
    font: 'sans',
    fontLocked: true,
    mock: 'catalogue',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    codeLabel: 'ARCHIVE',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.84;color:#202020;letter-spacing:0.005em;padding:18px 18px 34px;background-color:#ffffff;word-break:break-word;box-sizing:border-box;min-height:100%;`,
      h1: `font-size:2.05em;font-weight:780;text-align:left;color:#080808;margin:0.7em 0 0.38em;max-width:85%;line-height:1.12;letter-spacing:-0.035em;`,
      h1WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.25em;font-weight:650;line-height:1.2;letter-spacing:0.08em;margin-bottom:1.4em;">A–2026–MD / WHITE CUBE CATALOGUE</span>`,
      h2: `font-size:1.2em;font-weight:720;text-align:left;color:#111111;margin:2.6em 0 0.9em;padding:0.75em 0 0;border-top:1px solid #d7d7d7;line-height:1.35;letter-spacing:0;`,
      h2WrapOpen: `<span style="display:inline-block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.5em;font-weight:600;letter-spacing:0.05em;margin-right:1.2em;vertical-align:0.25em;">EXHIBIT</span>`,
      h3: `font-size:0.98em;font-weight:720;color:#111111;margin:1.9em 0 0.65em;padding-bottom:0.5em;border-bottom:1px solid #dddddd;line-height:1.45;`,
      h4: `font-family:Menlo,Consolas,monospace;font-size:0.78em;font-weight:650;color:${p};margin:1.6em 0 0.55em;line-height:1.5;letter-spacing:0.08em;text-transform:uppercase;`,
      h5: `font-size:0.88em;font-weight:680;color:#222222;margin:1.45em 0 0.5em;line-height:1.5;`,
      h6: `font-family:Menlo,Consolas,monospace;font-size:0.7em;font-weight:600;color:#7b7b7b;margin:1.3em 0 0.45em;line-height:1.5;letter-spacing:0.08em;`,
      p: `margin:0 0 1.28em;max-width:94%;line-height:1.9;`,
      liP: `margin:0 0 0.32em;line-height:1.75;`,
      blockquote: `margin:1.9em 0;padding:0.35em 0 0.35em 1.25em;background-color:transparent;border-left:3px solid ${p};border-radius:0;color:#222222;font-size:0.95em;line-height:1.82;`,
      bqP: `margin:0;`,
      ul: `margin:0.9em 0 1.45em;padding-left:1.4em;list-style-type:square;`,
      ol: `margin:0.9em 0 1.45em;padding-left:1.75em;`,
      li: `margin:0.46em 0;padding-left:0.22em;`,
      a: `color:${p};text-decoration:none;border-bottom:1px solid ${p};padding-bottom:1px;`,
      strong: `font-weight:760;color:#090909;`,
      em: `font-style:italic;color:#4d4d4d;`,
      s: `color:#9c9c9c;text-decoration-color:#777777;text-decoration-thickness:1px;`,
      mark: `background-color:#e7ebff;color:#0b2ba9;padding:1px 3px;border-radius:0;`,
      img: `display:block;max-width:100%;margin:1.6em auto;border-radius:0;box-shadow:none;filter:grayscale(100%);`,
      gallery: `margin:1.7em 0;padding:0;background-color:#ffffff;`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:0;filter:grayscale(100%);`,
      caption: `display:block;text-align:left;font-size:0.7em;color:#363636;margin:-0.8em 0 1.5em;line-height:1.55;letter-spacing:0.02em;`,
      hr: `border:none;border-top:1px solid #d7d7d7;margin:2.4em 0;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.8em;background-color:#f0f0f0;color:#333333;padding:2px 5px;border-radius:0;`,
      tableWrap: `overflow-x:auto;margin:1.55em 0;border-top:1px solid #cfcfcf;border-bottom:1px solid #cfcfcf;`,
      table: `width:100%;min-width:500px;border-collapse:collapse;font-size:0.78em;line-height:1.5;`,
      th: `border:none;border-bottom:1px solid #bfc7e8;padding:9px 7px;background-color:transparent;color:${p};font-weight:700;text-align:left;`,
      td: `border:none;border-bottom:1px solid #e4e4e4;padding:8px 7px;color:#303030;`,
      pre: `background-color:#f2f2f2;border:none;border-radius:0;margin:1.55em 0;overflow:hidden;`,
      prePlain: `padding:15px 16px;overflow-x:auto;`,
      preCode: `color:#444444;`,
    }),
  },
  {
    id: 'pixel-quest',
    name: '像素任务',
    tag: '游戏 · 教程',
    description: '深靛 HUD、关卡标签与任务清单，让攻略和技术教程更有行动感。',
    primary: '#16d9e5',
    font: 'sans',
    fontLocked: true,
    mock: 'pixel',
    surface: '#050d25',
    previewFade: '#050d25',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'CONSOLE',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.78;color:#d9e1ee;letter-spacing:0.01em;padding:14px 14px 30px;background-color:#050d25;word-break:break-word;box-sizing:border-box;min-height:100%;`,
      h1: `font-size:1.9em;font-weight:900;text-align:left;color:#f4f7ff;margin:0.72em 8px 0.55em;padding:0 0 0.55em;border-bottom:2px solid ${p};line-height:1.16;letter-spacing:-0.02em;`,
      h1WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.28em;font-weight:700;line-height:1.2;letter-spacing:0.1em;margin-bottom:1.35em;">PIXEL QUEST MANUAL / PROGRESS 18%</span>`,
      h2: `font-size:1.32em;font-weight:850;text-align:left;color:#f0ff26;margin:2em 8px 0.78em;padding:0.55em 0.65em;border-top:1px solid ${p};border-bottom:1px solid ${p};line-height:1.28;letter-spacing:0.01em;`,
      h2WrapOpen: `<span style="display:block;color:${p};font-family:Menlo,Consolas,monospace;font-size:0.44em;font-weight:700;letter-spacing:0.1em;margin-bottom:0.55em;">STAGE / CHECKPOINT</span>`,
      h3: `font-family:Menlo,Consolas,monospace;font-size:0.9em;font-weight:750;color:${p};margin:1.65em 8px 0.65em;padding-left:0.75em;border-left:4px solid ${p};line-height:1.45;letter-spacing:0.06em;text-transform:uppercase;`,
      h4: `font-family:Menlo,Consolas,monospace;font-size:0.82em;font-weight:750;color:#f0ff26;margin:1.5em 8px 0.55em;line-height:1.5;letter-spacing:0.06em;`,
      h5: `font-size:0.9em;font-weight:750;color:#eef2ff;margin:1.4em 8px 0.5em;line-height:1.5;`,
      h6: `font-family:Menlo,Consolas,monospace;font-size:0.72em;font-weight:650;color:#7283a4;margin:1.25em 8px 0.45em;line-height:1.5;letter-spacing:0.1em;`,
      p: `margin:0 8px 1.22em;color:#c7d1e2;line-height:1.84;`,
      liP: `margin:0 0 0.34em;line-height:1.72;`,
      blockquote: `margin:1.55em 8px;padding:0.9em 1em;background-color:#071631;border:1px solid ${p};border-left:6px solid ${p};border-radius:0;color:#ecf3ff;font-size:0.94em;line-height:1.75;`,
      bqP: `margin:0;`,
      ul: `margin:0.85em 8px 1.35em;padding-left:1.45em;list-style-type:square;color:#dce5f4;`,
      ol: `margin:0.85em 8px 1.35em;padding-left:1.75em;color:#dce5f4;list-style-type:decimal-leading-zero;`,
      li: `margin:0.5em 0;padding:0.12em 0 0.12em 0.28em;border-bottom:1px solid #10254b;`,
      a: `color:${p};text-decoration:none;border-bottom:1px dashed ${p};padding-bottom:1px;`,
      strong: `font-weight:850;color:#f0ff26;`,
      em: `font-style:italic;color:#8debf2;`,
      s: `color:#66738d;text-decoration-color:#ff5370;text-decoration-thickness:2px;`,
      mark: `background-color:#f0ff26;color:#07111f;padding:1px 4px;border-radius:0;`,
      img: `display:block;max-width:100%;margin:1.35em auto;border:2px solid ${p};border-radius:0;box-shadow:none;image-rendering:pixelated;`,
      gallery: `margin:1.45em 8px;padding:5px;border:1px solid ${p};background-color:#03091a;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #173d65;border-radius:0;box-sizing:border-box;image-rendering:pixelated;`,
      caption: `display:block;text-align:left;font-family:Menlo,Consolas,monospace;font-size:0.68em;color:${p};margin:-0.55em 0 1.3em;letter-spacing:0.05em;`,
      hr: `border:none;border-top:1px dashed ${p};margin:2em 8px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.82em;background-color:#102349;color:#ff6f91;padding:2px 6px;border:1px solid #1d426f;border-radius:0;`,
      tableWrap: `overflow-x:auto;margin:1.45em 8px;border:1px solid ${p};`,
      table: `width:100%;min-width:560px;border-collapse:collapse;font-family:Menlo,Consolas,monospace;font-size:0.76em;line-height:1.5;`,
      th: `border:1px solid #1e5570;padding:8px;background-color:#0b1b39;color:${p};font-weight:700;text-align:left;`,
      td: `border:1px solid #173754;padding:8px;color:#d9e1ee;`,
      pre: `background-color:#030817;border:1px solid ${p};border-radius:0;margin:1.45em 8px;overflow:hidden;`,
      preHeader: `padding:8px 12px;border-bottom:1px solid #1a5064;font-size:0;line-height:0;background-color:#071631;`,
      preLabel: `color:#f0ff26;font-size:10px;font-weight:700;line-height:12px;margin:0;letter-spacing:0.1em;vertical-align:top;`,
      preBody: `background-color:#030817;padding:13px 14px 15px;margin:0;overflow-x:auto;`,
      preCode: `color:#d9e1ee;`,
    }),
  },
  {
    id: 'velocity-report',
    name: '疾速赛报',
    tag: '体育 · 数据',
    description: '压缩黑体、竞速红与计分板结构，适合赛事复盘和数据报道。',
    primary: '#e01824',
    font: 'sans',
    fontLocked: true,
    mock: 'race',
    surface: '#f7f7f5',
    previewFade: '#f7f7f5',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'TELEMETRY',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.72;color:#171717;letter-spacing:-0.005em;padding:12px 12px 28px;background-color:#f7f7f5;word-break:break-word;box-sizing:border-box;min-height:100%;`,
      h1: `display:flex;align-items:flex-start;justify-content:space-between;gap:0.5em;font-size:2.08em;font-weight:950;font-style:italic;text-align:left;color:#080808;margin:0.55em 8px 0.5em;padding:0 0 0.45em;border-bottom:3px solid #111111;line-height:1.02;letter-spacing:-0.06em;`,
      h1WrapClose: `<span aria-hidden="true" style="flex:0 0 auto;color:${p};font-size:1.85em;font-weight:950;font-style:italic;line-height:0.8;letter-spacing:-0.08em;">07</span>`,
      h2: `font-size:1.38em;font-weight:900;text-align:left;color:#090909;margin:1.85em 8px 0.75em;padding:0.55em 0 0 0.75em;border-top:2px solid #111111;border-left:7px solid ${p};line-height:1.2;letter-spacing:-0.025em;`,
      h2WrapOpen: `<span style="display:inline-block;color:${p};font-size:0.48em;font-style:italic;font-weight:900;letter-spacing:0.02em;margin-right:0.8em;vertical-align:0.25em;">LAP /</span>`,
      h3: `font-size:1.08em;font-weight:850;color:#111111;margin:1.55em 8px 0.62em;padding-left:0.65em;border-left:5px solid ${p};line-height:1.32;`,
      h4: `font-size:0.88em;font-weight:850;font-style:italic;color:${p};margin:1.45em 8px 0.52em;line-height:1.45;letter-spacing:0.035em;text-transform:uppercase;`,
      h5: `font-size:0.9em;font-weight:800;color:#151515;margin:1.35em 8px 0.48em;line-height:1.45;`,
      h6: `font-family:Menlo,Consolas,monospace;font-size:0.7em;font-weight:700;color:#777777;margin:1.25em 8px 0.44em;line-height:1.45;letter-spacing:0.08em;`,
      p: `margin:0 8px 1.12em;line-height:1.78;`,
      liP: `margin:0 0 0.3em;line-height:1.65;`,
      blockquote: `margin:1.45em 8px;padding:1em 1.15em;background-color:#0b0b0b;border-left:8px solid ${p};border-radius:0;color:#ffffff;font-size:1.03em;font-weight:700;line-height:1.6;`,
      bqP: `margin:0;`,
      ul: `margin:0.78em 8px 1.3em;padding-left:1.4em;list-style-type:square;`,
      ol: `margin:0.78em 8px 1.3em;padding-left:1.8em;list-style-type:decimal-leading-zero;`,
      li: `margin:0.42em 0;padding:0.38em 0 0.38em 0.35em;border-bottom:1px solid #d3d3d3;`,
      a: `color:${p};font-weight:700;text-decoration:none;border-bottom:2px solid ${p};padding-bottom:1px;`,
      strong: `font-weight:900;color:${p};`,
      em: `font-style:italic;color:#454545;`,
      s: `color:#929292;text-decoration-color:${p};text-decoration-thickness:2px;`,
      mark: `background-color:${p};color:#ffffff;padding:1px 4px;border-radius:0;`,
      img: `display:block;max-width:100%;margin:1.25em auto;border-radius:0;box-shadow:none;`,
      gallery: `margin:1.35em 8px;padding:0;border-bottom:5px solid ${p};`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #f7f7f5;border-radius:0;box-sizing:border-box;`,
      caption: `display:block;text-align:left;font-size:0.7em;font-weight:650;color:#555555;margin:-0.5em 0 1.25em;padding-left:0.65em;border-left:4px solid ${p};line-height:1.5;`,
      hr: `border:none;border-top:3px solid #111111;margin:2em 8px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.82em;background-color:#111111;color:#ffffff;padding:2px 6px;border-radius:0;`,
      tableWrap: `overflow-x:auto;margin:1.35em 8px;border-top:3px solid #111111;border-bottom:2px solid #111111;`,
      table: `width:100%;min-width:520px;border-collapse:collapse;font-size:0.76em;line-height:1.42;`,
      th: `border:1px solid #2d2d2d;padding:8px 7px;background-color:#101010;color:#ffffff;font-weight:800;text-align:left;`,
      td: `border:1px solid #d6d6d6;padding:8px 7px;color:#151515;`,
      pre: `background-color:#090909;border:none;border-radius:0;margin:1.4em 8px;overflow:hidden;`,
      preHeader: `padding:8px 12px;border-bottom:1px solid #3a3a3a;font-size:0;line-height:0;background-color:#111111;`,
      preLabel: `color:${p};font-size:10px;font-weight:800;line-height:12px;margin:0;letter-spacing:0.1em;vertical-align:top;`,
      preBody: `background-color:#090909;padding:13px 14px 15px;margin:0;overflow-x:auto;`,
      preCode: `color:#e7e7e7;`,
    }),
  },

  // ---------- 设计稿精选（01–10） ----------

  {
    id: 'mobai',
    name: '墨白',
    tag: '留白极简',
    description: '大量留白与发丝线，黑色只做最克制的强调。',
    primary: '#111111',
    font: 'sans',
    fontLocked: true,
    mock: 'plain',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: () => ({
      h1WrapOpen: `<span style="display:block;font-size:0.42em;font-weight:400;color:#bbbbbb;letter-spacing:0.35em;margin-bottom:2em;">MOBAI · 墨白</span>`,
      h1: `font-size:1.55em;font-weight:700;text-align:center;color:#111111;margin:1em 8px 0.6em;line-height:1.5;letter-spacing:0.04em;`,
      h2: `font-size:1.19em;font-weight:700;color:#111111;margin:2.2em 8px 1em;padding-bottom:0.6em;border-bottom:1px solid #eeeeee;line-height:1.5;`,
      h3: `font-size:1.05em;font-weight:700;color:#111111;margin:1.8em 8px 0.7em;line-height:1.5;`,
      h4: `font-size:1em;font-weight:700;color:#111111;margin:1.5em 8px 0.6em;line-height:1.5;`,
      blockquote: `margin:1.8em 8px;padding:0 0 0 1.2em;background-color:transparent;border-left:1px solid #dddddd;border-radius:0;color:#999999;font-size:0.94em;line-height:2;`,
      strong: `font-weight:600;color:#000000;border-bottom:1px solid #cccccc;`,
      em: `font-style:italic;color:#666666;`,
      s: `color:#a1a1aa;`,
      mark: `background-color:#f2f2f2;color:#111111;padding:0 2px;`,
      a: `color:#111111;text-decoration:none;border-bottom:1px solid #111111;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border-radius:4px;box-shadow:0 4px 14px rgba(0,0,0,0.06);`,
      hr: `border:none;border-top:1px solid #dddddd;margin:2.6em auto;width:32px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f4f4f5;color:#111111;padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #e4e4e7;padding:8px 12px;background-color:#f4f4f5;font-weight:600;text-align:left;`,
    }),
  },
  {
    id: 'klein',
    name: '克莱因蓝',
    tag: '单色主义',
    description: '只用克莱因蓝、黑与白，整条蓝带章节号。',
    primary: '#002FA7',
    font: 'sans',
    fontLocked: true,
    mock: 'pill',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    extractH2Index: true,
    styles: (p) => ({
      h1WrapOpen: `<span style="display:block;font-size:0.35em;font-weight:400;color:#9db8ff;letter-spacing:0.3em;margin-bottom:1.6em;">KLEIN BLUE</span>`,
      h1: `font-size:1.9em;font-weight:900;text-align:left;color:#111111;margin:0.8em 8px 0.5em;line-height:1.3;`,
      h2: `font-size:1.05em;font-weight:700;color:#ffffff;background-color:${p};margin:2.4em 8px 1.2em;padding:0.6em 0.95em;letter-spacing:0.06em;line-height:1.5;`,
      h2Index: `color:#9db8ff;font-size:0.85em;font-weight:400;letter-spacing:0.15em;margin-right:0.7em;`,
      h3: `font-size:1.05em;font-weight:700;color:${p};margin:1.8em 8px 0.7em;line-height:1.5;`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#eef2fb;border:none;border-radius:2px;color:${p};font-size:0.95em;line-height:1.9;`,
      strong: `font-weight:700;color:${p};`,
      em: `font-style:italic;color:#4a5a7a;`,
      s: `color:#9aa7c2;`,
      mark: `background-color:#dbe4f7;color:${p};padding:0 2px;`,
      a: `color:${p};text-decoration:none;border-bottom:1px solid ${p};`,
      img: `display:block;max-width:100%;margin:1.3em auto;border:2px solid ${p};border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid ${p};box-sizing:border-box;border-radius:0;`,
      hrHtml: `<p style="text-align:center;margin:2.4em 0;font-size:0;line-height:0;"><span style="display:inline-block;width:8px;height:8px;background-color:${p};margin:0 6px;"></span><span style="display:inline-block;width:8px;height:8px;background-color:${p};margin:0 6px;"></span><span style="display:inline-block;width:8px;height:8px;background-color:${p};margin:0 6px;"></span></p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#eef2fb;color:${p};padding:2px 6px;border-radius:3px;`,
      th: `border:1px solid ${p};padding:8px 12px;background-color:${p};color:#ffffff;font-weight:700;text-align:left;`,
      td: `border:1px solid #c7d4f2;padding:8px 12px;`,
    }),
  },
  {
    id: 'xuanzhi',
    name: '宣纸',
    tag: '东方古典',
    description: '宣纸底色、宋体卷气，印章红点到为止。',
    primary: '#c2352b',
    font: 'serif',
    fontLocked: true,
    mock: 'lines',
    surface: '#f7f4ec',
    previewFade: '#f7f4ec',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:2;color:#2b2b2b;letter-spacing:0.05em;padding:20px 20px 34px;background-color:#f7f4ec;word-break:break-word;`,
      h1WrapOpen: `<span style="display:block;font-size:0.4em;font-weight:400;color:#8a7156;letter-spacing:0.45em;margin-bottom:2em;">東方既白</span>`,
      h1: `font-size:1.6em;font-weight:600;text-align:center;color:#2b2b2b;margin:1em 8px 0.7em;letter-spacing:0.28em;line-height:1.8;`,
      h2: `font-size:1.2em;font-weight:600;text-align:center;color:#2b2b2b;margin:2.4em 8px 1.3em;letter-spacing:0.12em;line-height:1.6;`,
      h2WrapOpen: `<span style="display:inline-block;width:30px;border-top:1px solid #d8cbb0;vertical-align:5px;margin-right:12px;"></span>`,
      h2WrapClose: `<span style="display:inline-block;width:30px;border-top:1px solid #d8cbb0;vertical-align:5px;margin-left:12px;"></span>`,
      h3: `font-size:1.05em;font-weight:600;color:#2b2b2b;margin:1.8em 8px 0.7em;letter-spacing:0.08em;line-height:1.6;`,
      p: `margin:0 8px 1.3em;text-indent:2em;text-align:justify;`,
      blockquote: `margin:1.8em 8px;padding:0;background-color:transparent;border:none;color:#6b5d4f;font-size:1em;line-height:2.2;letter-spacing:0.15em;text-align:center;`,
      bqP: `margin:0;text-align:center;text-indent:0;`,
      strong: `font-weight:700;color:${p};`,
      em: `font-style:italic;color:#6b5d4f;`,
      s: `color:#a89373;`,
      mark: `background-color:#efe4c8;color:#8a5a2b;padding:0 2px;`,
      a: `color:${p};text-decoration:none;border-bottom:1px solid ${p};`,
      img: `display:block;max-width:100%;margin:1.4em auto;padding:6px;border:1px solid #d8cbb0;background-color:#fdfaf3;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #d8cbb0;box-sizing:border-box;border-radius:0;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a89373;margin:-0.4em 0 1.2em;letter-spacing:0.12em;`,
      hrHtml: `<p style="text-align:center;color:${p};letter-spacing:0.6em;margin:2.4em 0;font-size:0.8em;">◆ ◆ ◆</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f0ead8;color:#8a7156;padding:2px 6px;border-radius:0;`,
      th: `border:1px solid #d8cbb0;padding:8px 12px;background-color:#f0ead8;color:#2b2b2b;font-weight:600;text-align:left;`,
      td: `border:1px solid #d8cbb0;padding:8px 12px;`,
    }),
  },
  {
    id: 'morandi-green',
    name: '莫兰迪绿',
    tag: '灰调治愈',
    description: '低饱和灰绿与柔对比，安静不抢内容。',
    primary: '#7d8c7a',
    font: 'sans',
    fontLocked: true,
    mock: 'under',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: () => ({
      h1WrapOpen: `<span style="display:block;font-size:0.42em;font-weight:400;color:#a8b5a0;letter-spacing:0.4em;margin-bottom:2.2em;">MORANDI GREEN</span>`,
      h1: `font-size:1.5em;font-weight:500;text-align:center;color:#46524a;margin:1em 8px 0.6em;letter-spacing:0.08em;line-height:1.7;`,
      h2: `font-size:1.15em;font-weight:600;color:#46524a;margin:2.4em 8px 1.2em;letter-spacing:0.05em;line-height:1.6;`,
      h2WrapOpen: `<span style="border-bottom:4px solid #c3cfc0;padding-bottom:5px;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:1.1em 1.2em;background-color:#f1f4ef;border:none;border-radius:14px;color:#7c8779;font-size:0.94em;line-height:2;`,
      strong: `font-weight:600;color:#46524a;`,
      em: `font-style:italic;color:#7c8779;`,
      s: `color:#a8b5a0;`,
      mark: `background-color:#e3e9dd;color:#46524a;padding:0 2px;border-radius:2px;`,
      a: `color:#6b7b6e;text-decoration:none;border-bottom:1px solid #a8b5a0;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border-radius:8px;box-shadow:0 8px 20px rgba(107,123,110,0.16);`,
      hr: `border:none;border-top:1px solid #dfe4dc;margin:2.8em auto;width:48px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f1f4ef;color:#5c6660;padding:2px 6px;border-radius:5px;`,
      th: `border:1px solid #dfe4dc;padding:8px 12px;background-color:#f1f4ef;color:#46524a;font-weight:600;text-align:left;`,
      td: `border:1px solid #dfe4dc;padding:8px 12px;`,
    }),
  },
  {
    id: 'midnight-gold',
    name: '午夜蓝金',
    tag: '商务周刊',
    description: '藏青与金的评论员版式，克制而有分量。',
    primary: '#1b2a4a',
    font: 'sans',
    fontLocked: true,
    mock: 'under',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'label',
    codeLabel: 'MIDNIGHT',
    styles: () => ({
      h1WrapOpen: `<span style="display:block;font-family:Georgia,'Times New Roman',serif;font-size:0.4em;font-weight:400;color:#c9a063;letter-spacing:0.4em;margin-bottom:1.8em;">MIDNIGHT REVIEW</span>`,
      h1: `font-size:1.55em;font-weight:700;text-align:center;color:#1b2a4a;margin:1em 8px 0.6em;line-height:1.5;letter-spacing:0.03em;`,
      h2: `font-size:1.15em;font-weight:700;color:#1b2a4a;margin:2.4em 8px 1.1em;letter-spacing:0.04em;line-height:1.5;`,
      h2WrapOpen: `<span style="display:block;width:28px;height:3px;background-color:#c9a063;margin-bottom:0.6em;"></span>`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.1em;background-color:#faf8f4;border-left:2px solid #c9a063;border-radius:0;color:#5a6478;font-size:0.95em;line-height:1.9;`,
      strong: `font-weight:700;color:#1b2a4a;border-bottom:1px solid #c9a063;`,
      em: `font-style:italic;color:#5a6478;`,
      s: `color:#9aa3b2;`,
      mark: `background-color:#f4ecd9;color:#8a6d2f;padding:0 2px;`,
      a: `color:#1b2a4a;text-decoration:none;border-bottom:1px solid #c9a063;`,
      img: `display:block;max-width:100%;margin:1.4em auto;padding:5px;border:1px solid #e5dcc8;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#9aa3b2;margin:-0.5em 0 1.2em;`,
      hr: `border:none;border-top:1px solid #c9a063;margin:2.6em auto;width:60px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#faf8f4;color:#1b2a4a;padding:2px 6px;border-radius:3px;`,
      th: `border:1px solid #e5dcc8;padding:9px 12px;background-color:#1b2a4a;color:#ffffff;font-weight:600;text-align:left;`,
      td: `border:1px solid #e5dcc8;padding:8px 12px;`,
    }),
  },
  {
    id: 'cream-orange',
    name: '奶油橘子',
    tag: '甜品菜单',
    description: '不规则奶油色块与圆体，软糯但有秩序。',
    primary: '#ef8a17',
    font: 'rounded',
    fontLocked: true,
    mock: 'pill',
    surface: '#fff9f0',
    previewFade: '#fff9f0',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.85;color:#4a3b2c;letter-spacing:0.02em;padding:20px 18px 32px;background-color:#fff9f0;word-break:break-word;`,
      h1: `font-size:1.45em;font-weight:700;text-align:center;color:#4a3b2c;margin:1.2em 8px 0.8em;line-height:1.6;`,
      h1WrapOpen: `<span style="background-color:#ffd9a3;border-radius:16px 6px 16px 6px;padding:0.3em 0.8em;display:inline-block;">`,
      h1WrapClose: `</span>`,
      h2: `font-size:1.1em;font-weight:700;color:#4a3b2c;margin:2.2em 8px 1.2em;line-height:1.6;`,
      h2WrapOpen: `<span style="background-color:#ef8a17;border-radius:6px 14px 6px 14px;padding:0.3em 0.9em;color:#ffffff;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#ffedd6;border:none;border-radius:18px;color:#8a6d4a;font-size:0.95em;line-height:1.9;text-align:center;`,
      bqP: `margin:0;text-align:center;text-indent:0;`,
      strong: `font-weight:700;color:#e07b00;`,
      em: `font-style:normal;color:#c19b72;`,
      s: `color:#c19b72;`,
      mark: `background-color:#ffe3ba;color:#b35c00;padding:0 2px;border-radius:3px;`,
      a: `color:#e07b00;font-weight:600;text-decoration:none;border-bottom:1px dashed #ef8a17;`,
      img: `display:block;max-width:100%;margin:1.4em auto;border-radius:18px;box-shadow:0 8px 20px rgba(239,138,23,0.18);`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:12px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#c19b72;margin:-0.5em 0 1.2em;`,
      hrHtml: `<p style="text-align:center;color:#ef8a17;letter-spacing:0.5em;margin:2.4em 0;font-size:0.75em;">● ● ●</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#ffedd6;color:#b35c00;padding:2px 6px;border-radius:5px;`,
      th: `border:1px solid #efd3a8;padding:8px 12px;background-color:#ffd9a3;color:#4a3b2c;font-weight:700;text-align:left;`,
      td: `border:1px solid #efd3a8;padding:8px 12px;`,
    }),
  },
  {
    id: 'mint-soda',
    name: '薄荷气泡',
    tag: '轻盈圆角',
    description: '虚线、胶囊与薄荷绿，夏天的透气感。',
    primary: '#2fbf9b',
    font: 'rounded',
    fontLocked: true,
    mock: 'outline',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: () => ({
      h1: `font-size:1.5em;font-weight:700;text-align:center;color:#1e6b5a;margin:1.2em 8px 0.6em;line-height:1.6;`,
      h2: `font-size:1.15em;font-weight:700;color:#1e6b5a;margin:2.2em 8px 1.1em;padding-bottom:0.5em;border-bottom:2px dotted #9fdcc9;line-height:1.5;`,
      h2WrapOpen: `<span style="color:#2fbf9b;font-size:0.75em;margin-right:0.5em;">●</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#e8f8f3;border:none;border-radius:18px;color:#4a8a7a;font-size:0.95em;line-height:1.8;`,
      bqP: `margin:0;text-indent:0;`,
      strong: `font-weight:700;color:#1e6b5a;`,
      em: `font-style:normal;color:#7ab3a5;`,
      s: `color:#9fdcc9;`,
      mark: `background-color:#c9f2e6;color:#1e6b5a;padding:0 4px;border-radius:6px;`,
      a: `color:#2fbf9b;font-weight:600;text-decoration:none;border-bottom:1px solid #9fdcc9;`,
      img: `display:block;max-width:100%;margin:1.4em auto;border-radius:22px;box-shadow:0 8px 20px rgba(47,191,155,0.15);`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:14px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#7ab3a5;margin:-0.5em 0 1.2em;`,
      hrHtml: `<section style="width:56px;height:3px;border-radius:2px;margin:2.6em auto;background-color:#2fbf9b;background-image:linear-gradient(90deg,#2fbf9b,#9fdcc9);"></section>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#e8f8f3;color:#1e6b5a;padding:2px 6px;border-radius:6px;`,
      th: `border:1px solid #bfe8dc;padding:8px 12px;background-color:#e8f8f3;color:#1e6b5a;font-weight:700;text-align:left;`,
      td: `border:1px solid #bfe8dc;padding:8px 12px;`,
    }),
  },
  {
    id: 'brick-industry',
    name: '红砖工业',
    tag: '工业档案',
    description: '等宽字体、警示条纹与验收章，硬核但讲究。',
    primary: '#b5402f',
    font: 'sans',
    fontLocked: true,
    mock: 'industry',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'BUILD',
    styles: () => ({
      h1WrapOpen: `<span style="display:block;font-family:Menlo,Consolas,monospace;font-size:0.45em;font-weight:400;color:#6a6a66;letter-spacing:0.15em;margin-bottom:1.5em;">FILE NO. 008</span>`,
      h1: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:1.5em;font-weight:800;color:#2a2a28;margin:0.8em 8px 0.6em;letter-spacing:0.04em;line-height:1.45;`,
      h2: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.95em;font-weight:700;color:#ffffff;background-color:#2a2a28;border-left:6px solid #b5402f;margin:2.2em 8px 1.2em;padding:0.55em 0.9em;letter-spacing:0.08em;line-height:1.5;`,
      h3: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.95em;font-weight:700;color:#b5402f;margin:1.8em 8px 0.7em;letter-spacing:0.06em;line-height:1.45;`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.1em;background-color:#f0efec;border-left:4px solid #b5402f;border-radius:0;color:#6a6a66;font-size:0.94em;line-height:1.8;`,
      strong: `font-weight:700;color:#b5402f;`,
      em: `font-style:italic;color:#6a6a66;`,
      s: `color:#8a8a86;`,
      mark: `background-color:#f8dcd4;color:#8c2f22;padding:0 2px;`,
      a: `color:#b5402f;font-weight:600;text-decoration:none;border-bottom:2px solid #b5402f;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border:3px solid #2a2a28;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:2px solid #2a2a28;box-sizing:border-box;border-radius:0;`,
      caption: `display:block;font-family:Menlo,Consolas,monospace;font-size:0.72em;color:#8a8a86;margin:-0.5em 0 1.2em;`,
      hrHtml: `<section style="height:8px;margin:2.4em 8px;background-color:#2a2a28;background-image:repeating-linear-gradient(45deg,#b5402f 0,#b5402f 12px,transparent 12px,transparent 24px);"></section>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.85em;background-color:#2a2a28;color:#f0b4a8;padding:2px 6px;border-radius:0;`,
      th: `border:1px solid #2a2a28;padding:8px 12px;background-color:#2a2a28;color:#ffffff;font-family:Menlo,Consolas,monospace;font-weight:700;text-align:left;`,
      td: `border:1px solid #2a2a28;padding:8px 12px;`,
      pre: `background-color:#2a2a28;border:none;border-radius:0;margin:1.4em 8px;overflow:hidden;`,
      preHeader: `padding:9px 12px;border-bottom:1px solid #4a4a48;font-size:0;line-height:0;background-color:#2a2a28;`,
      preLabel: `font-family:Menlo,Consolas,monospace;color:#f0b4a8;font-size:10px;font-weight:700;line-height:12px;letter-spacing:0.12em;vertical-align:top;`,
      preBody: `background-color:#2a2a28;padding:13px 14px;margin:0;overflow-x:auto;`,
      preCode: `color:#e8e0da;`,
    }),
  },
  {
    id: 'mori-journal',
    name: '森系手帐',
    tag: '日记胶带',
    description: '和纸胶带标题与拍立得照片框，慢生活手帐。',
    primary: '#3a6b4f',
    font: 'rounded',
    fontLocked: true,
    mock: 'pill',
    surface: '#f7f5ef',
    previewFade: '#f7f5ef',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.9;color:#45503f;letter-spacing:0.02em;padding:20px 18px 32px;background-color:#f7f5ef;word-break:break-word;`,
      h1: `font-size:1.45em;font-weight:600;text-align:center;color:#3a6b4f;margin:1.2em 8px 0.5em;line-height:1.7;`,
      h2: `font-size:1.1em;font-weight:600;color:#3a6b4f;margin:2.2em 8px 1.2em;line-height:1.6;`,
      h2WrapOpen: `<span style="background-color:rgba(58,107,79,0.16);border-radius:3px;padding:0.3em 0.9em;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.1em;background-color:#f0f4ec;border-left:3px solid #8db39a;border-radius:0 8px 8px 0;color:#6b7f6d;font-size:0.94em;line-height:1.9;`,
      strong: `font-weight:700;color:#3a6b4f;`,
      em: `font-style:normal;color:#93a08d;`,
      s: `color:#a3a58d;`,
      mark: `background-color:#dcead3;color:#3a6b4f;padding:0 3px;border-radius:3px;`,
      a: `color:#3a6b4f;text-decoration:none;border-bottom:1px dashed #8db39a;`,
      img: `display:block;max-width:100%;margin:1.6em auto;padding:10px 10px 30px;background-color:#ffffff;border:1px solid #e3dccb;box-shadow:0 6px 16px rgba(90,80,60,0.12);border-radius:0;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #e3dccb;box-sizing:border-box;border-radius:0;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a3a58d;margin:-0.8em 0 1.4em;`,
      hrHtml: `<p style="text-align:center;color:#8db39a;margin:2.4em 0;">❀</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f0f4ec;color:#3a6b4f;padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #c8d8c0;padding:8px 12px;background-color:#dcead3;color:#3a6b4f;font-weight:700;text-align:left;`,
      td: `border:1px solid #c8d8c0;padding:8px 12px;`,
    }),
  },
  {
    id: 'fleet-street',
    name: '英伦报纸',
    tag: '复古报社',
    description: '刊头双线、宋体大字与社论版式。',
    primary: '#8c1f28',
    font: 'serif',
    fontLocked: true,
    mock: 'frame',
    surface: '#fbf9f4',
    previewFade: '#fbf9f4',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:Georgia,'Times New Roman',${font};font-size:${fs}px;line-height:1.9;color:#1a1a1a;letter-spacing:0.02em;padding:20px 18px 32px;background-color:#fbf9f4;word-break:break-word;`,
      h1WrapOpen: `<span style="display:block;font-family:Georgia,'Times New Roman',serif;font-size:0.38em;font-weight:400;letter-spacing:0.45em;color:#8a8578;margin-bottom:1.6em;">THE SLOW LIFE GAZETTE</span>`,
      h1: `font-size:1.8em;font-weight:900;text-align:center;color:#1a1a1a;margin:0.8em 8px 0.5em;line-height:1.4;`,
      h2: `font-size:1.2em;font-weight:700;text-align:center;color:#1a1a1a;margin:2.2em 8px 1.2em;padding:0.4em 0;border-top:1px solid #1a1a1a;border-bottom:1px solid #1a1a1a;line-height:1.6;`,
      blockquote: `margin:1.8em 8px;padding:0;background-color:transparent;border:none;color:#1a1a1a;font-size:1.05em;line-height:2;text-align:center;font-style:italic;`,
      bqP: `margin:0;text-align:center;text-indent:0;`,
      strong: `font-weight:700;color:#8c1f28;`,
      em: `font-style:italic;color:#4a4538;`,
      s: `color:#8a8578;`,
      mark: `background-color:#f0e6c8;color:#1a1a1a;padding:0 2px;`,
      a: `color:#8c1f28;text-decoration:none;border-bottom:1px solid #8c1f28;`,
      img: `display:block;max-width:100%;margin:1.4em auto;padding:6px;border:1px solid #1a1a1a;background-color:#ffffff;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      caption: `display:block;text-align:center;font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:0.78em;color:#8a8578;margin:-0.4em 0 1.2em;`,
      hr: `border:none;border-top:3px solid #1a1a1a;margin:2.4em auto;width:40px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.85em;background-color:#f0ede4;color:#1a1a1a;padding:2px 6px;border-radius:0;`,
      th: `border:1px solid #1a1a1a;padding:8px 12px;background-color:#f0ede4;font-weight:700;text-align:left;`,
      td: `border:1px solid #1a1a1a;padding:8px 12px;`,
    }),
  },
  {
    id: 'blueprint',
    name: '蓝图',
    tag: '工程图纸',
    description: '蓝底网格、虚线注释框与尺寸线，硬核技术美学。',
    primary: '#7fd4ff',
    font: 'sans',
    fontLocked: true,
    mock: 'band',
    surface: '#16407f',
    previewFade: '#16407f',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'DRAWING',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.85;color:#eef3fb;letter-spacing:0.03em;padding:20px 18px 26px;background-color:#16407f;background-image:repeating-linear-gradient(0deg,rgba(255,255,255,0.05) 0,rgba(255,255,255,0.05) 1px,transparent 1px,transparent 24px),repeating-linear-gradient(90deg,rgba(255,255,255,0.05) 0,rgba(255,255,255,0.05) 1px,transparent 1px,transparent 24px);word-break:break-word;`,
      h1WrapOpen: `<span style="display:block;font-family:Menlo,Consolas,monospace;font-size:0.45em;font-weight:400;color:#7fd4ff;letter-spacing:0.15em;margin-bottom:1.5em;">PROJECT: SLOW-LIFE-001</span>`,
      h1: `font-size:1.65em;font-weight:800;color:#ffffff;margin:0.8em 8px 0.5em;line-height:1.5;letter-spacing:0.03em;`,
      h2: `font-size:1.1em;font-weight:700;color:#ffffff;margin:2.2em 8px 1.2em;padding:0.6em 0.85em;border:1px solid rgba(127,212,255,0.55);letter-spacing:0.05em;line-height:1.5;`,
      h3: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.95em;font-weight:700;color:#7fd4ff;margin:1.8em 8px 0.7em;letter-spacing:0.08em;line-height:1.45;`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.1em;background-color:transparent;border:1px dashed rgba(127,212,255,0.6);border-radius:0;color:#7fd4ff;font-size:0.9em;line-height:1.8;`,
      strong: `font-weight:700;color:#7fd4ff;`,
      em: `font-style:italic;color:#b8d4f0;`,
      s: `color:#6f8ab5;`,
      mark: `background-color:rgba(127,212,255,0.25);color:#ffffff;padding:0 2px;`,
      a: `color:#7fd4ff;text-decoration:none;border-bottom:1px solid #7fd4ff;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border:1px solid rgba(255,255,255,0.6);border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid rgba(255,255,255,0.35);box-sizing:border-box;border-radius:0;`,
      caption: `display:block;font-family:Menlo,Consolas,monospace;font-size:0.72em;color:rgba(255,255,255,0.5);margin:-0.5em 0 1.2em;`,
      hrHtml: `<section style="display:flex;align-items:center;margin:2.4em 8px;"><span style="width:1px;height:10px;background-color:#7fd4ff;"></span><span style="flex:1;border-top:1px solid #7fd4ff;"></span><span style="width:1px;height:10px;background-color:#7fd4ff;"></span></section>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.85em;background-color:rgba(0,0,0,0.25);color:#7fd4ff;padding:2px 6px;border-radius:0;`,
      th: `border:1px solid rgba(255,255,255,0.4);padding:8px 12px;background-color:rgba(127,212,255,0.15);color:#ffffff;font-weight:700;text-align:left;`,
      td: `border:1px solid rgba(255,255,255,0.3);padding:8px 12px;`,
      pre: `background-color:#0c2a57;border:1px solid rgba(127,212,255,0.4);border-radius:0;margin:1.4em 8px;overflow:hidden;`,
      preHeader: `padding:9px 12px;border-bottom:1px solid rgba(127,212,255,0.3);font-size:0;line-height:0;background-color:transparent;`,
      preLabel: `font-family:Menlo,Consolas,monospace;color:#7fd4ff;font-size:10px;font-weight:700;line-height:12px;letter-spacing:0.12em;vertical-align:top;`,
      preBody: `background-color:#0c2a57;padding:13px 14px;margin:0;overflow-x:auto;`,
      preCode: `color:#d8e6f7;`,
    }),
  },
  {
    id: 'peach-soda',
    name: '蜜桃苏打',
    tag: '汽水铺',
    description: '粉蓝双色的胶囊贴纸，清甜但克制。',
    primary: '#ff8fa3',
    font: 'rounded',
    fontLocked: true,
    mock: 'outline',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: () => ({
      h1: `font-size:1.45em;font-weight:700;text-align:center;color:#e0567a;margin:1.2em 8px 0.5em;line-height:1.6;`,
      h2: `font-size:1.1em;font-weight:700;color:#433a3d;margin:2.2em 8px 1.2em;line-height:1.6;`,
      h2WrapOpen: `<span style="background-color:#ff8fa3;border-radius:999px;padding:0.3em 1em;color:#ffffff;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#fff0f3;border:none;border-radius:18px;color:#a06672;font-size:0.95em;line-height:1.9;`,
      strong: `font-weight:700;color:#e0567a;`,
      em: `font-style:normal;color:#b8959c;`,
      s: `color:#c9a3ab;`,
      mark: `background-color:#ffe0e8;color:#e0567a;padding:0 4px;border-radius:6px;`,
      a: `color:#64b5f6;font-weight:600;text-decoration:none;border-bottom:1px solid #64b5f6;`,
      img: `display:block;max-width:100%;margin:1.4em auto;border-radius:18px;box-shadow:0 8px 20px rgba(255,143,163,0.2);`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:12px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#b8959c;margin:-0.5em 0 1.2em;`,
      hrHtml: `<p style="text-align:center;margin:2.4em 0;font-size:0.75em;letter-spacing:0.5em;"><span style="color:#ff8fa3;">●</span>&nbsp;<span style="color:#64b5f6;">●</span>&nbsp;<span style="color:#ff8fa3;">●</span></p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#fff0f3;color:#e0567a;padding:2px 6px;border-radius:6px;`,
      th: `border:1px solid #ffd0dc;padding:8px 12px;background-color:#ff8fa3;color:#ffffff;font-weight:700;text-align:left;`,
      td: `border:1px solid #ffd0dc;padding:8px 12px;`,
    }),
  },
  {
    id: 'mono-editorial',
    name: '黑白编辑',
    tag: '黑白力量',
    description: '黑底白字编号块与反白强调，编辑部式凌厉。',
    primary: '#000000',
    font: 'sans',
    fontLocked: true,
    mock: 'big',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    extractH2Index: true,
    styles: () => ({
      h1WrapOpen: `<span style="display:block;font-size:0.4em;font-weight:400;color:#999999;letter-spacing:0.3em;margin-bottom:1.8em;">NO.13 / EDITORIAL</span>`,
      h1: `font-size:1.9em;font-weight:900;color:#000000;margin:0.8em 8px 0.4em;line-height:1.3;letter-spacing:-0.03em;`,
      h2: `font-size:1.25em;font-weight:900;color:#000000;margin:2.4em 8px 1.1em;line-height:1.3;`,
      h2Index: `display:inline-block;background-color:#000000;color:#ffffff;font-size:0.8em;font-weight:800;padding:0.2em 0.6em;margin-right:0.8em;vertical-align:0.1em;`,
      blockquote: `margin:1.8em 8px;padding:1.1em 1.2em;background-color:transparent;border:3px solid #000000;border-radius:0;color:#000000;font-size:1em;font-weight:600;line-height:1.8;`,
      strong: `font-weight:800;color:#ffffff;background-color:#000000;padding:0 4px;`,
      em: `font-style:italic;color:#444444;`,
      s: `color:#999999;`,
      mark: `background-color:#e0e0e0;color:#000000;padding:0 2px;`,
      a: `color:#000000;font-weight:700;text-decoration:none;border-bottom:2px solid #000000;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border:2px solid #000000;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:1px solid #000000;box-sizing:border-box;border-radius:0;`,
      hr: `border:none;margin:2.4em auto;width:32px;height:4px;background-color:#000000;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.85em;font-weight:600;background-color:#f1f1f1;color:#000000;padding:2px 6px;border-radius:0;`,
      th: `border:2px solid #000000;padding:8px 12px;background-color:#000000;color:#ffffff;font-weight:800;text-align:left;`,
      td: `border:2px solid #000000;padding:8px 12px;`,
    }),
  },
  {
    id: 'lemon-sea',
    name: '柠檬海盐',
    tag: '荧光手账',
    description: '柠檬荧光笔扫过的标题与强调，海风般明亮。',
    primary: '#f5c518',
    font: 'sans',
    fontLocked: true,
    mock: 'highlight',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: () => ({
      h1: `font-size:1.5em;font-weight:800;text-align:center;color:#2f3e46;margin:1.2em 8px 0.6em;line-height:1.6;`,
      h2: `font-size:1.15em;font-weight:800;color:#2f3e46;margin:2.2em 8px 1.2em;line-height:1.8;`,
      h2WrapOpen: `<span style="background-image:linear-gradient(transparent 55%,#ffe27a 55%);padding:0 4px;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#f2f7f9;border:2px dashed #f5c518;border-radius:14px;color:#6b7f8c;font-size:0.94em;line-height:1.9;`,
      strong: `font-weight:700;color:#2f3e46;background-image:linear-gradient(transparent 60%,#fff3b0 60%);padding:0 2px;`,
      em: `font-style:italic;color:#6b7f8c;`,
      s: `color:#8fa1ab;`,
      mark: `background-color:#ffe27a;color:#2f3e46;padding:0 2px;`,
      a: `color:#6b7f8c;font-weight:600;text-decoration:none;border-bottom:2px solid #f5c518;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border-radius:14px;box-shadow:0 8px 20px rgba(107,127,140,0.18);`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:10px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#8fa1ab;margin:-0.5em 0 1.2em;`,
      hrHtml: `<p style="text-align:center;color:#f5c518;letter-spacing:0.5em;margin:2.4em 0;font-size:0.75em;">● ● ●</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f2f7f9;color:#2f3e46;padding:2px 6px;border-radius:5px;`,
      th: `border:1px solid #eed88f;padding:8px 12px;background-color:#f5c518;color:#2f3e46;font-weight:700;text-align:left;`,
      td: `border:1px solid #e3e9ed;padding:8px 12px;`,
    }),
  },
  {
    id: 'wisteria',
    name: '紫藤书屋',
    tag: '宋体书店',
    description: '细紫框章节与宋体诗行，旧书店的安静。',
    primary: '#5f4b87',
    font: 'serif',
    fontLocked: true,
    mock: 'outline',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:2;color:#4a4454;letter-spacing:0.04em;padding:20px 20px 34px;word-break:break-word;`,
      h1WrapOpen: `<span style="display:block;font-size:0.42em;font-weight:400;color:#a293bd;letter-spacing:0.45em;margin-bottom:2.2em;">紫藤書屋</span>`,
      h1: `font-size:1.5em;font-weight:600;text-align:center;color:#4a3d66;margin:1em 8px 0.6em;letter-spacing:0.15em;line-height:1.8;`,
      h2: `font-size:1.1em;font-weight:600;text-align:center;color:#5f4b87;margin:2.4em 8px 1.4em;line-height:1.6;`,
      h2WrapOpen: `<span style="border:1px solid #c3b8d9;padding:0.4em 1.4em;letter-spacing:0.1em;">`,
      h2WrapClose: `</span>`,
      p: `margin:0 8px 1.3em;text-indent:2em;text-align:justify;`,
      blockquote: `margin:1.8em 8px;padding:0;background-color:transparent;border:none;color:#8a7fa3;font-size:0.95em;line-height:2.3;text-align:center;font-style:italic;`,
      bqP: `margin:0;text-align:center;text-indent:0;`,
      strong: `font-weight:700;color:#5f4b87;`,
      em: `font-style:italic;color:#8a7fa3;`,
      s: `color:#a293bd;`,
      mark: `background-color:#ece5f5;color:#5f4b87;padding:0 2px;`,
      a: `color:#5f4b87;text-decoration:none;border-bottom:1px solid #c3b8d9;`,
      img: `display:block;max-width:100%;margin:1.4em auto;padding:5px;border:1px solid #d9d0e8;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a293bd;margin:-0.4em 0 1.2em;letter-spacing:0.1em;`,
      hrHtml: `<p style="text-align:center;color:#c3b8d9;margin:2.4em 0;">❧</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#ece5f5;color:#5f4b87;padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #d9d0e8;padding:8px 12px;background-color:#ece5f5;color:#5f4b87;font-weight:600;text-align:left;`,
      td: `border:1px solid #d9d0e8;padding:8px 12px;`,
    }),
  },
  {
    id: 'hk-neon',
    name: '港风复古',
    tag: '霓虹招牌',
    description: '墨绿招牌、朱红压边与金色点缀，老香港夜色。',
    primary: '#23483c',
    font: 'serif',
    fontLocked: true,
    mock: 'band',
    surface: '#f6f1e7',
    previewFade: '#f6f1e7',
    codeTheme: 'dark',
    codeChrome: 'label',
    codeLabel: 'HONGKONG',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.85;color:#3d3a33;letter-spacing:0.03em;padding:20px 18px 32px;background-color:#f6f1e7;word-break:break-word;`,
      h1WrapOpen: `<span style="display:block;font-size:0.42em;font-weight:400;color:#c9a227;letter-spacing:0.45em;margin-bottom:2em;">港島夜話</span>`,
      h1: `font-size:1.5em;font-weight:700;text-align:center;color:#23483c;margin:1em 8px 0.7em;letter-spacing:0.15em;line-height:1.7;`,
      h2: `font-size:1.1em;font-weight:700;color:#23483c;margin:2.2em 8px 1.2em;line-height:1.6;`,
      h2WrapOpen: `<span style="background-color:#23483c;color:#f6f1e7;letter-spacing:0.08em;padding:0.45em 1.1em;border-bottom:3px solid #d43d33;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.1em;background-color:#ede5d3;border-left:4px solid #c9a227;border-radius:0;color:#7a6a4f;font-size:0.94em;line-height:1.9;`,
      strong: `font-weight:700;color:#d43d33;`,
      em: `font-style:italic;color:#7a6a4f;`,
      s: `color:#9a8c6f;`,
      mark: `background-color:#f0e3bd;color:#7a5c1a;padding:0 2px;`,
      a: `color:#d43d33;text-decoration:none;border-bottom:1px solid #d43d33;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border:3px solid #23483c;border-radius:0;box-shadow:none;box-sizing:border-box;`,
      galleryImg: `display:block;width:100%;margin:0;border:2px solid #23483c;box-sizing:border-box;border-radius:0;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#9a8c6f;margin:-0.5em 0 1.2em;`,
      hrHtml: `<p style="text-align:center;margin:2.4em 0;"><span style="display:inline-block;width:40px;border-top:2px solid #c9a227;"></span></p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#ede5d3;color:#7a6a4f;padding:2px 6px;border-radius:0;`,
      th: `border:1px solid #23483c;padding:8px 12px;background-color:#23483c;color:#f6f1e7;font-weight:700;text-align:left;`,
      td: `border:1px solid #c9bfa5;padding:8px 12px;`,
    }),
  },
  {
    id: 'nordic',
    name: '北欧',
    tag: '细字留白',
    description: '细字重、大间距与发丝线，冷净的呼吸感。',
    primary: '#22303c',
    font: 'sans',
    fontLocked: true,
    mock: 'plain',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:2.05;color:#4a5560;letter-spacing:0.03em;padding:24px 22px 40px;word-break:break-word;`,
      h1: `font-size:1.7em;font-weight:300;text-align:center;color:#22303c;margin:1.4em 8px 0.7em;letter-spacing:0.05em;line-height:1.6;`,
      h2: `font-size:1.2em;font-weight:500;color:#22303c;margin:2.8em 8px 1.2em;letter-spacing:0.03em;line-height:1.5;`,
      h3: `font-size:1.05em;font-weight:500;color:#22303c;margin:2em 8px 0.8em;letter-spacing:0.03em;line-height:1.5;`,
      blockquote: `margin:1.8em 8px;padding:1.2em 1.3em;background-color:#f5f7f9;border:none;border-radius:4px;color:#7a8894;font-size:0.94em;line-height:2;`,
      strong: `font-weight:600;color:#22303c;`,
      em: `font-style:italic;color:#7a8894;`,
      s: `color:#9fb0ba;`,
      mark: `background-color:#eef3f6;color:#4a5560;padding:0 2px;`,
      a: `color:#22303c;text-decoration:none;border-bottom:1px solid #8fa3b3;`,
      img: `display:block;max-width:100%;margin:1.5em auto;border-radius:2px;box-shadow:none;`,
      caption: `display:block;text-align:center;font-size:0.74em;color:#9fb0ba;margin:-0.6em 0 1.4em;letter-spacing:0.1em;`,
      hr: `border:none;border-top:1px solid #e3e9ed;margin:2.8em 0;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f5f7f9;color:#22303c;padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #e3e9ed;padding:8px 12px;background-color:#f5f7f9;font-weight:600;text-align:left;`,
      td: `border:1px solid #e3e9ed;padding:8px 12px;`,
    }),
  },
  {
    id: 'latte',
    name: '咖啡拉花',
    tag: '咖啡馆',
    description: '奶泡底色、拿铁圆点与豆单表格，街角暖意。',
    primary: '#6f4e37',
    font: 'rounded',
    fontLocked: true,
    mock: 'under',
    surface: '#faf6f1',
    previewFade: '#faf6f1',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      container: `font-family:${font};font-size:${fs}px;line-height:1.85;color:#4a3a30;letter-spacing:0.02em;padding:20px 18px 32px;background-color:#faf6f1;word-break:break-word;`,
      h1: `font-size:1.5em;font-weight:700;text-align:center;color:#4a3626;margin:1.2em 8px 0.5em;line-height:1.6;`,
      h2: `font-size:1.15em;font-weight:700;color:#6f4e37;margin:2.2em 8px 1.1em;padding-bottom:0.5em;border-bottom:1px solid #e8ddcf;line-height:1.5;`,
      h2WrapOpen: `<span style="color:#d9c3ac;font-size:0.7em;margin-right:0.5em;">●</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#f0e7db;border:none;border-radius:14px;color:#8a7360;font-size:0.94em;line-height:1.9;`,
      strong: `font-weight:700;color:#6f4e37;`,
      em: `font-style:normal;color:#a8917a;`,
      s: `color:#b39b84;`,
      mark: `background-color:#f0e2cd;color:#6f4e37;padding:0 3px;border-radius:4px;`,
      a: `color:#6f4e37;font-weight:600;text-decoration:none;border-bottom:1px dashed #d9c3ac;`,
      img: `display:block;max-width:100%;margin:1.4em auto;border-radius:14px;box-shadow:0 8px 20px rgba(111,78,55,0.18);`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:10px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a8917a;margin:-0.5em 0 1.2em;`,
      hrHtml: `<p style="text-align:center;color:#d9c3ac;letter-spacing:0.5em;margin:2.4em 0;font-size:0.75em;">● ● ●</p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#f0e7db;color:#6f4e37;padding:2px 6px;border-radius:5px;`,
      th: `border:1px solid #e0d5c5;padding:8px 12px;background-color:#d9c3ac;color:#4a3626;font-weight:700;text-align:left;`,
      td: `border:1px solid #e0d5c5;padding:8px 12px;`,
    }),
  },
  {
    id: 'cyan-scape',
    name: '青绿山水',
    tag: '千里江山',
    description: '青绿渐变的山脊标题块，当代古典的矿物色。',
    primary: '#2f6f6a',
    font: 'serif',
    fontLocked: true,
    mock: 'dopa',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'light',
    codeChrome: 'plain',
    styles: (p, fs, font) => ({
      h1WrapOpen: `<span style="display:block;font-size:0.42em;font-weight:400;color:#7fb5a2;letter-spacing:0.45em;margin-bottom:2.2em;">千里江山</span>`,
      h1: `font-size:1.55em;font-weight:700;text-align:center;color:#2f6f6a;margin:1em 8px 0.5em;letter-spacing:0.12em;line-height:1.7;`,
      h2: `font-size:1.1em;font-weight:700;color:#2f6f6a;margin:2.4em 8px 1.3em;line-height:1.6;`,
      h2WrapOpen: `<span style="background-color:#2f6f6a;background-image:linear-gradient(120deg,#2f6f6a,#5fa092);color:#ffffff;letter-spacing:0.08em;padding:0.45em 1.15em;border-radius:4px 18px 4px 18px;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:0.9em 1.2em;background-color:#eef4f1;border-left:3px solid #7fb5a2;border-radius:0 12px 12px 0;color:#5a7269;font-size:0.94em;line-height:2;`,
      strong: `font-weight:700;color:#2f6f6a;`,
      em: `font-style:italic;color:#5a7269;`,
      s: `color:#7a948b;`,
      mark: `background-color:#d4e7df;color:#2f6f6a;padding:0 2px;`,
      a: `color:#2f6f6a;text-decoration:none;border-bottom:1px solid #7fb5a2;`,
      img: `display:block;max-width:100%;margin:1.4em auto;border-radius:4px 18px 4px 18px;box-shadow:none;`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:4px 12px 4px 12px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#7a948b;margin:-0.5em 0 1.2em;`,
      hrHtml: `<section style="width:60px;height:3px;border-radius:2px;margin:2.6em auto;background-color:#5fa092;background-image:linear-gradient(90deg,#2f6f6a,#7fb5a2);"></section>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#eef4f1;color:#2f6f6a;padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #cfe0d8;padding:8px 12px;background-color:#2f6f6a;color:#ffffff;font-weight:700;text-align:left;`,
      td: `border:1px solid #cfe0d8;padding:8px 12px;`,
    }),
  },
  {
    id: 'candy-pop',
    name: '糖果波普',
    tag: '波普海报',
    description: '粉蓝黄三色、粗黑标题与蓝色硬阴影，快乐有秩序。',
    primary: '#ff5da2',
    font: 'rounded',
    fontLocked: true,
    mock: 'brutal',
    surface: '#ffffff',
    previewFade: '#ffffff',
    codeTheme: 'dark',
    codeChrome: 'plain',
    styles: () => ({
      h1: `font-size:1.7em;font-weight:900;text-align:center;color:#222222;margin:1.2em 8px 0.6em;line-height:1.4;`,
      h2: `font-size:1.25em;font-weight:900;color:#222222;margin:2.2em 8px 1.2em;line-height:1.7;`,
      h2WrapOpen: `<span style="display:block;font-size:0.45em;font-weight:400;letter-spacing:0.4em;margin-bottom:0.3em;"><span style="color:#ff5da2;">●</span> <span style="color:#4d7cff;">●</span> <span style="color:#ffd23f;">●</span></span><span style="border-bottom:4px solid #ff5da2;padding-bottom:4px;">`,
      h2WrapClose: `</span>`,
      blockquote: `margin:1.8em 8px;padding:1em 1.2em;background-color:#f4f8ff;border:2px dashed #4d7cff;border-radius:16px;color:#4d7cff;font-size:0.95em;font-weight:600;line-height:1.8;`,
      blockquoteNested: `margin:0.8em 0 0.4em;padding:0.15em 0 0.15em 0.9em;background-color:transparent;border:none;border-left:3px solid #4d7cff;border-radius:0;color:#4d7cff;box-sizing:border-box;max-width:100%;`,
      strong: `font-weight:700;color:#ffffff;background-color:#ff5da2;padding:0 6px;border-radius:5px;`,
      em: `font-style:normal;color:#a0a8b8;`,
      s: `color:#a0a8b8;`,
      mark: `background-color:#ffd23f;color:#222222;padding:0 3px;border-radius:3px;`,
      a: `color:#4d7cff;font-weight:700;text-decoration:none;border-bottom:2px solid #ffd23f;`,
      img: `display:block;max-width:100%;margin:1.5em auto;border-radius:16px;box-shadow:7px 7px 0 #4d7cff;`,
      galleryImg: `display:block;width:100%;margin:0;border-radius:10px;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a0a8b8;margin:-0.6em 0 1.3em;`,
      hrHtml: `<p style="text-align:center;margin:2.4em 0;font-size:0.85em;letter-spacing:0.4em;"><span style="color:#ff5da2;">●</span>&nbsp;<span style="color:#4d7cff;">●</span>&nbsp;<span style="color:#ffd23f;">●</span></p>`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.85em;font-weight:600;background-color:#f4f8ff;color:#4d7cff;padding:2px 6px;border-radius:6px;`,
      th: `border:1px solid #ffc2da;padding:8px 12px;background-color:#ff5da2;color:#ffffff;font-weight:700;text-align:left;`,
      td: `border:1px solid #ffc2da;padding:8px 12px;`,
    }),
  },
  {
    id: 'tech-blue',
    name: '科技蓝',
    tag: '技术 · 教程',
    description: '移植自 mdnice 经典「科技蓝」：蓝色竖条标题、灰青投影卡片引用与渐变分隔线。',
    primary: '#0e88eb',
    font: 'sans',
    mock: 'band',
    surface: '#ffffff',
    previewFade: '#ffffff',
    styles: (p) => ({
      // 主色贯穿标题 / 强调 / 引用；引用与图片统一灰青大投影（#84a1a8）；
      // 代码块沿用默认 Mac 深色窗口（mdnice 上与科技蓝的经典搭配）
      h1: `font-size:1.5em;font-weight:700;text-align:center;color:${p};margin:1.6em 8px 0.9em;padding-bottom:0.3em;border-bottom:2px solid ${p};line-height:1.5;`,
      h2: `font-size:1.3em;font-weight:700;color:${p};margin:1.8em 8px 0.9em;padding-left:0.5em;border-left:5px solid ${p};line-height:1.5;`,
      h3: `font-size:1.1em;font-weight:700;color:${p};margin:1.6em 8px 0.7em;line-height:1.5;`,
      h4: `font-size:1em;font-weight:700;color:${p};margin:1.4em 8px 0.6em;line-height:1.5;`,
      blockquote: `margin:1.8em 8px 2.2em;padding:0.8em 1.1em 0.9em;background-color:#ffffff;border-radius:0 0 10px 10px;box-shadow:0 10px 15px #84a1a8;color:${p};font-size:0.94em;line-height:1.8;`,
      bqWrapOpen: `<span style="display:block;font-size:1.9em;line-height:1.1;font-weight:700;color:${p};">❝</span>`,
      bqP: `margin:0;`,
      strong: `font-weight:700;color:${p};`,
      em: `font-style:italic;color:${p};`,
      a: `color:${p};font-weight:600;text-decoration:none;`,
      img: `display:block;max-width:100%;margin:1.4em auto 2.2em;border-radius:0 0 5px 5px;box-shadow:0 10px 15px #84a1a8;`,
      caption: `display:block;text-align:center;font-size:0.76em;color:#a1a1aa;margin:-1.4em 0 1.4em;letter-spacing:0.04em;`,
      hr: `border:none;height:1px;background-color:${p};background-image:linear-gradient(to right,rgba(14,136,235,0),${p},rgba(14,136,235,0));margin:2.2em 16px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:rgba(27,31,35,0.05);color:${p};padding:2px 6px;border-radius:4px;`,
      th: `border:1px solid #e4e4e7;padding:8px 12px;background-color:${p}14;color:${p};font-weight:700;text-align:left;`,
      td: `border:1px solid #e4e4e7;padding:8px 12px;`,
    }),
  },
  {
    id: 'fullstack-blue',
    name: '全栈蓝',
    tag: '全栈 · 笔记',
    description: '移植自 mdnice 经典「全栈蓝」：网格稿纸底、蓝条标题与浅蓝边框引用卡。',
    primary: '#40b8fa',
    font: 'sans',
    mock: 'band',
    surface: '#ffffff',
    previewFade: '#ffffff',
    styles: (p, fs, font) => ({
      // 三档蓝：主色 #40b8fa / 强调 #3594f7 / 线条 #3baafa；透明度变体用 8 位
      // hex 写成主色前缀，强调色联动时正则替换连同透明度一起换算。
      // 原版 h2/h3 图标与 strong 的「」缀饰依赖伪元素和外链图，以内联形式适配。
      container: `font-family:${font};font-size:${fs}px;line-height:1.8;color:#2b2b2b;letter-spacing:0.05em;padding:0 8px;background-image:repeating-linear-gradient(0deg,rgba(50,0,0,0.04) 0,rgba(50,0,0,0.04) 1px,transparent 1px,transparent 20px),repeating-linear-gradient(90deg,rgba(50,0,0,0.04) 0,rgba(50,0,0,0.04) 1px,transparent 1px,transparent 20px);`,
      h1: `font-size:1.55em;font-weight:700;text-align:center;color:${p};margin:1.5em 8px 0.9em;line-height:1.5;letter-spacing:0.05em;`,
      h2WrapOpen: `<span style="display:inline-block;width:0.8em;height:0.8em;line-height:0.8em;font-size:0.8em;background-color:${p}80;border-radius:0.2em;margin-right:0.5em;overflow:hidden;">&nbsp;</span>`,
      h2: `font-size:1.25em;font-weight:700;color:${p};margin:1.8em 8px 1em;padding-bottom:0.3em;border-bottom:4px solid ${p};line-height:1.5;`,
      h3: `font-size:1.06em;font-weight:700;text-align:center;color:#2b2b2b;margin:1.7em 8px 0.8em;line-height:1.7;`,
      h3WrapOpen: `<span style="border-bottom:2px solid ${p}a6;padding-bottom:3px;">`,
      h3WrapClose: `</span>`,
      h4: `font-size:1em;font-weight:700;color:#2b2b2b;margin:1.4em 8px 0.6em;line-height:1.5;`,
      li: `margin:0.4em 0;color:#595959;`,
      blockquote: `margin:1.6em 8px;padding:0.7em 1em 0.8em;background-color:${p}1a;border:1px solid ${p}66;border-radius:6px;color:#595959;font-size:0.94em;line-height:1.7;`,
      bqWrapOpen: `<span style="display:block;font-size:1.9em;line-height:1.1;font-weight:700;color:${p}80;">❝</span>`,
      bqWrapClose: `<span style="display:block;font-size:1.4em;line-height:1;font-weight:700;color:${p}80;text-align:right;">❞</span>`,
      bqP: `margin:0;`,
      strong: `font-weight:700;color:#3594f7;`,
      em: `font-style:normal;font-weight:700;color:#3594f7;`,
      s: `color:#3594f7;text-decoration-thickness:1px;`,
      a: `color:${p};text-decoration:none;border-bottom:1px solid #3baafa;`,
      img: `display:block;max-width:100%;margin:1.3em auto;border-radius:6px;box-shadow:2px 4px 7px rgba(0,0,0,0.35);`,
      caption: `display:block;text-align:center;font-size:0.8em;color:#2b2b2b;margin:-0.5em 0 1.2em;`,
      hr: `border:none;border-top:2px solid #3baafa;margin:2em 16px;`,
      code: `font-family:Menlo,Consolas,'Courier New',monospace;font-size:0.86em;background-color:#3baafa1a;color:#3594f7;padding:1px 4px;border-radius:2px;`,
      th: `border:1px solid ${p}66;padding:8px 12px;background-color:${p}1f;color:#2b2b2b;font-weight:700;text-align:left;`,
      td: `border:1px solid ${p}40;padding:8px 12px;color:#595959;`,
    }),
  },
]

// ---------- 强调色联动 ----------
// 用户改强调色时，主题主色整体替换；下表中的辅助色按规则同步换算：
// 数字 = 向白色混合的比例（浅色），'deep' = 向黑色混合 35%（深色文字/描边）。
const ACCENT_TINTS = {
  klein: { '#eef2fb': 0.93, '#dbe4f7': 0.85, '#c7d4f2': 0.75, '#9db8ff': 0.5 },
  'morandi-green': { '#46524a': 'deep', '#6b7b6e': 'deep', '#c3cfc0': 0.65, '#f1f4ef': 0.93, '#e3e9dd': 0.85, '#a8b5a0': 0.4, '#5c6660': 'deep', '#7c8779': 0.3 },
  'cream-orange': { '#ffd9a3': 0.75, '#ffedd6': 0.88, '#ffe3ba': 0.8, '#e07b00': 'deep', '#b35c00': 'deep', '#efd3a8': 0.7 },
  'mint-soda': { '#1e6b5a': 'deep', '#e8f8f3': 0.92, '#c9f2e6': 0.8, '#9fdcc9': 0.6, '#4a8a7a': 0.35, '#bfe8dc': 0.7, '#f2fbf8': 0.95 },
  'brick-industry': { '#f0b4a8': 0.7, '#f8dcd4': 0.85 },
  'mori-journal': { '#dcead3': 0.8, '#f0f4ec': 0.92, '#8db39a': 0.4, '#c8d8c0': 0.7 },
  'peach-soda': { '#e0567a': 'deep', '#fff0f3': 0.92, '#ffe0e8': 0.8, '#a06672': 0.35, '#ffd0dc': 0.7, '#b8959c': 0.4 },
  'lemon-sea': { '#ffe27a': 0.7, '#fff3b0': 0.8, '#f2f7f9': 0.93, '#2f3e46': 'deep', '#6b7f8c': 0.3, '#eed88f': 0.6 },
  wisteria: { '#4a3d66': 'deep', '#ece5f5': 0.9, '#c3b8d9': 0.6, '#8a7fa3': 0.35, '#d9d0e8': 0.75 },
  'hk-neon': { '#ede5d3': 0.9, '#f0e3bd': 0.85 },
  latte: { '#d9c3ac': 0.6, '#f0e7db': 0.9, '#f0e2cd': 0.85, '#e8ddcf': 0.75, '#e0d5c5': 0.7, '#8a7360': 0.3, '#4a3626': 'deep' },
  'cyan-scape': { '#5fa092': 0.3, '#7fb5a2': 0.5, '#eef4f1': 0.93, '#d4e7df': 0.8, '#cfe0d8': 0.75, '#5a7269': 0.25 },
  'candy-pop': { '#ffc2da': 0.75 },
  // 强调蓝 / 线条蓝与主色同族，联动时直接跟随用户所选主色
  'fullstack-blue': { '#3594f7': 0, '#3baafa': 0 },
}

// 灰黑系主题的正文/标题就是主色本身，全局替换会毁掉正文可读性，故关闭联动
const ACCENT_REPLACE_OFF = new Set(['mobai', 'mono-editorial', 'nordic'])

// 辅色槽位：主题里独立于主色的配色（不随主色联动），允许用户单独调整。
// base = 精确替换的代表色；also = 一并精确替换的同族色；
// tints = 按用户所选颜色派生（规则同 ACCENT_TINTS：数字向白混合，'deep' 向黑混合 35%）。
export const COLOR_SLOTS = {
  'night-film': [
    { key: 'cream', label: '标题暖白', base: '#fff0d7', also: ['#f7ead6', '#f3e6d2'] },
  ],
  'pixel-quest': [
    { key: 'neon', label: '荧光黄', base: '#f0ff26' },
    { key: 'pink', label: '点缀粉', base: '#ff5370', also: ['#ff6f91'] },
  ],
  'midnight-gold': [
    { key: 'gold', label: '鎏金', base: '#c9a063', tints: { '#8a6d2f': 'deep', '#f4ecd9': 0.85 } },
  ],
  'peach-soda': [{ key: 'blue', label: '撞色蓝', base: '#64b5f6' }],
  'hk-neon': [
    { key: 'gold', label: '招牌金', base: '#c9a227', tints: { '#7a5c1a': 'deep' } },
    { key: 'red', label: '霓虹红', base: '#d43d33' },
  ],
  'candy-pop': [
    { key: 'blue', label: '点缀蓝', base: '#4d7cff', tints: { '#f4f8ff': 0.94 } },
    { key: 'yellow', label: '点缀黄', base: '#ffd23f' },
  ],
  'tech-blue': [{ key: 'shadow', label: '投影灰青', base: '#84a1a8' }],
}

function mixHex(hexA, hexB, ratio) {
  const a = parseInt(hexA.slice(1), 16)
  const b = parseInt(hexB.slice(1), 16)
  const r = Math.round(((a >> 16) & 255) + (((b >> 16) & 255) - ((a >> 16) & 255)) * ratio)
  const g = Math.round(((a >> 8) & 255) + (((b >> 8) & 255) - ((a >> 8) & 255)) * ratio)
  const bl = Math.round((a & 255) + ((b & 255) - (a & 255)) * ratio)
  return `#${((1 << 24) + (r << 16) + (g << 8) + bl).toString(16).slice(1)}`
}

const tintOf = (hex, whiteRatio) => mixHex(hex, '#ffffff', whiteRatio)
const deepenOf = (hex) => mixHex(hex, '#000000', 0.35)
const escapeReg = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

// 合成最终样式表：基础样式 + 主题覆盖 + 用户自定义覆盖
export function buildStyles(theme, opts = {}) {
  const p = opts.accent || theme.primary
  const fs = opts.fontSize || 16
  const fontKey = opts.fontFamily && opts.fontFamily !== 'theme' ? opts.fontFamily : theme.font || 'sans'
  const font = FONT_STACKS[fontKey] || FONT_STACKS.sans
  const themed = Object.assign(baseStyles(p, fs, font), theme.styles(p, fs, font))

  // 强调色联动：主色整体替换 + 辅助色按表换算；用户自定义样式在其后合并，不受影响
  const replacements = []
  if (opts.accent && !ACCENT_REPLACE_OFF.has(theme.id)) {
    replacements.push([theme.primary, p])
    for (const [hex, mode] of Object.entries(ACCENT_TINTS[theme.id] || {})) {
      replacements.push([hex, mode === 'deep' ? deepenOf(p) : tintOf(p, Number(mode) || 0)])
    }
  }
  // 辅色槽位：独立于主色的配色按用户选择替换（浅底/深色变体随之派生）
  for (const slot of COLOR_SLOTS[theme.id] || []) {
    const chosen = opts.slotColors?.[slot.key]
    if (typeof chosen !== 'string' || !chosen) continue
    replacements.push([slot.base, chosen])
    for (const hex of slot.also || []) replacements.push([hex, chosen])
    for (const [hex, mode] of Object.entries(slot.tints || {})) {
      replacements.push([hex, mode === 'deep' ? deepenOf(chosen) : tintOf(chosen, Number(mode) || 0)])
    }
  }
  if (replacements.length) {
    for (const key of Object.keys(themed)) {
      let value = themed[key]
      if (typeof value !== 'string') continue
      for (const [from, to] of replacements) {
        value = value.replace(new RegExp(escapeReg(from), 'gi'), to)
      }
      themed[key] = value
    }
  }

  const styles = Object.assign(themed, opts.custom || {})

  // 跨主题的排版安全线：长 token 必须能在当前行断开；列表不应继承引用块
  // 或自定义容器的居中 / 首行缩进，否则 marker 会与正文分离。
  styles.container = `${styles.container}word-break:break-word;overflow-wrap:anywhere;`
  styles.ul = `${styles.ul}text-align:left;text-indent:0;list-style-position:outside;`
  styles.ol = `${styles.ol}text-align:left;text-indent:0;list-style-position:outside;`
  styles.li = `${styles.li}text-align:left;text-indent:0;`
  styles.liP = `${styles.liP}text-align:left;text-indent:0;`
  styles.bqP = `${styles.bqP}text-indent:0;`
  if (!styles.blockquoteNested) {
    // 嵌套引用降阶：剥掉外层引用的背景、虚线框与全边框，只留左边线，
    // 避免“泡中泡”事故。优先复用外层左边框颜色，其次主题主色。
    const borderColor =
      (styles.blockquote.match(/border-left:\s*\d+px\s+\w+\s+([^;]+);/) || [])[1]?.trim() || p
    styles.blockquoteNested = `margin:0.8em 0 0.4em;padding:0.15em 0 0.15em 0.9em;background-color:transparent;border:none;border-left:3px solid ${borderColor};border-radius:0;color:inherit;box-sizing:border-box;max-width:100%;`
  }

  return styles
}
// 主题分类：主题库面板的筛选 Tab 使用（简约 / 书卷 / 杂志 / 商务 / 科技 / 活力）
export const themeCategories = {
  literary: '书卷',
  'swiss-index': '杂志',
  'night-film': '杂志',
  'white-cube': '简约',
  'pixel-quest': '科技',
  'velocity-report': '杂志',
  mobai: '简约',
  klein: '简约',
  xuanzhi: '书卷',
  'morandi-green': '简约',
  'midnight-gold': '商务',
  'cream-orange': '活力',
  'mint-soda': '活力',
  'brick-industry': '科技',
  'mori-journal': '杂志',
  'fleet-street': '杂志',
  blueprint: '科技',
  'peach-soda': '活力',
  'mono-editorial': '杂志',
  'lemon-sea': '活力',
  wisteria: '书卷',
  'hk-neon': '书卷',
  nordic: '简约',
  latte: '活力',
  'cyan-scape': '书卷',
  'candy-pop': '活力',
  'tech-blue': '科技',
  'fullstack-blue': '科技',
}

export const categoryOrder = ['全部', '收藏', '简约', '书卷', '杂志', '商务', '科技', '活力']
