ALTER TABLE sources ADD COLUMN kind TEXT NOT NULL DEFAULT 'rss';
ALTER TABLE sources ADD COLUMN config TEXT NOT NULL DEFAULT '{}';
ALTER TABLE sources ADD COLUMN first_party INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sources ADD COLUMN participation_mode TEXT NOT NULL DEFAULT 'editorial';
ALTER TABLE sources ADD COLUMN interval_minutes INTEGER NOT NULL DEFAULT 120;
ALTER TABLE sources ADD COLUMN source_tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE sources ADD COLUMN owner_entity_id TEXT;
ALTER TABLE sources ADD COLUMN created INTEGER NOT NULL DEFAULT 0;
UPDATE sources SET config=json_object('feedUrl',url);
UPDATE sources SET first_party=1 WHERE id IN ('rss-openai-news','rss-google-deepmind','rss-google-research','rss-hugging-face','rss-microsoft-research','rss-nvidia-blog','rss-aws-ml','rss-github-ai','rss-mistral','rss-bair');
ALTER TABLE receipts ADD COLUMN model TEXT;
ALTER TABLE receipts ADD COLUMN purpose TEXT;
ALTER TABLE receipts ADD COLUMN created INTEGER;
CREATE TABLE IF NOT EXISTS admin_sessions (token_hash TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_attempts (key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,subject TEXT,reason TEXT,before_value TEXT,after_value TEXT,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_commands (key TEXT PRIMARY KEY,result TEXT NOT NULL,created INTEGER NOT NULL);
ALTER TABLE items ADD COLUMN visibility TEXT NOT NULL DEFAULT 'public';
ALTER TABLE items ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE items ADD COLUMN updated INTEGER NOT NULL DEFAULT 0;
ALTER TABLE feedback ADD COLUMN email TEXT;
ALTER TABLE feedback ADD COLUMN page_url TEXT;
ALTER TABLE feedback ADD COLUMN screenshot TEXT;
ALTER TABLE feedback ADD COLUMN source_hash TEXT;
ALTER TABLE feedback ADD COLUMN status TEXT NOT NULL DEFAULT 'new';
ALTER TABLE feedback ADD COLUMN note TEXT;
ALTER TABLE feedback ADD COLUMN updated INTEGER NOT NULL DEFAULT 0;
