CREATE TABLE IF NOT EXISTS selected_ledger (seq INTEGER PRIMARY KEY AUTOINCREMENT,item_id TEXT NOT NULL,op TEXT NOT NULL,payload TEXT,changed INTEGER NOT NULL);
CREATE INDEX selected_ledger_item ON selected_ledger(item_id,seq);
CREATE TRIGGER selected_insert AFTER INSERT ON items WHEN NEW.stage='done' AND NEW.visibility='public' AND NEW.selected=1 AND NEW.archived=0
BEGIN INSERT INTO selected_ledger(item_id,op,payload,changed) VALUES(NEW.id,'upsert',json_object('id',NEW.id,'title',COALESCE(NEW.title_zh,NEW.title),'originalTitle',NEW.title,'summary',NEW.summary_zh,'source',json_object('name',(SELECT name FROM sources WHERE id=NEW.source_id)),'publishedAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.published/1000.0,'unixepoch'),'discoveredAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.discovered/1000.0,'unixepoch'),'category',NEW.category,'score',CASE WHEN NEW.score1 IS NOT NULL AND NEW.score2 IS NOT NULL THEN (NEW.score1+NEW.score2)/2.0 ELSE NULL END,'selected',json('true'),'reason',NEW.reason,'links',json_object('aihot','https://zoci.pro/tools/ai-hot/items/'||NEW.id,'original',NEW.url)),strftime('%s','now')*1000); END;
CREATE TRIGGER selected_update AFTER UPDATE ON items WHEN (NEW.stage='done' AND NEW.visibility='public' AND NEW.selected=1 AND NEW.archived=0) OR (OLD.stage='done' AND OLD.visibility='public' AND OLD.selected=1 AND OLD.archived=0)
BEGIN INSERT INTO selected_ledger(item_id,op,payload,changed) VALUES(NEW.id,CASE WHEN NEW.stage='done' AND NEW.visibility='public' AND NEW.selected=1 AND NEW.archived=0 THEN 'upsert' ELSE 'remove' END,CASE WHEN NEW.stage='done' AND NEW.visibility='public' AND NEW.selected=1 AND NEW.archived=0 THEN json_object('id',NEW.id,'title',COALESCE(NEW.title_zh,NEW.title),'originalTitle',NEW.title,'summary',NEW.summary_zh,'source',json_object('name',(SELECT name FROM sources WHERE id=NEW.source_id)),'publishedAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.published/1000.0,'unixepoch'),'discoveredAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.discovered/1000.0,'unixepoch'),'category',NEW.category,'score',CASE WHEN NEW.score1 IS NOT NULL AND NEW.score2 IS NOT NULL THEN (NEW.score1+NEW.score2)/2.0 ELSE NULL END,'selected',json('true'),'reason',NEW.reason,'links',json_object('aihot','https://zoci.pro/tools/ai-hot/items/'||NEW.id,'original',NEW.url)) ELSE NULL END,strftime('%s','now')*1000); END;
CREATE TRIGGER selected_delete AFTER DELETE ON items WHEN OLD.stage='done' AND OLD.visibility='public' AND OLD.selected=1 AND OLD.archived=0
BEGIN INSERT INTO selected_ledger(item_id,op,payload,changed) VALUES(OLD.id,'remove',NULL,strftime('%s','now')*1000); END;
INSERT INTO selected_ledger(item_id,op,payload,changed) SELECT NEW.id,'upsert',json_object('id',NEW.id,'title',COALESCE(NEW.title_zh,NEW.title),'originalTitle',NEW.title,'summary',NEW.summary_zh,'source',json_object('name',(SELECT name FROM sources WHERE id=NEW.source_id)),'publishedAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.published/1000.0,'unixepoch'),'discoveredAt',strftime('%Y-%m-%dT%H:%M:%fZ',NEW.discovered/1000.0,'unixepoch'),'category',NEW.category,'score',CASE WHEN NEW.score1 IS NOT NULL AND NEW.score2 IS NOT NULL THEN (NEW.score1+NEW.score2)/2.0 ELSE NULL END,'selected',json('true'),'reason',NEW.reason,'links',json_object('aihot','https://zoci.pro/tools/ai-hot/items/'||NEW.id,'original',NEW.url)),strftime('%s','now')*1000 FROM items NEW WHERE NEW.stage='done' AND NEW.visibility='public' AND NEW.selected=1 AND NEW.archived=0;
CREATE TABLE item_overrides (item_id TEXT PRIMARY KEY,fields TEXT NOT NULL,base TEXT NOT NULL,reason TEXT,version INTEGER NOT NULL DEFAULT 0,updated INTEGER NOT NULL);
